FROM golang:1.5.1
MAINTAINER gou@portworx.com

RUN \
  apt-get update -yq && \
  apt-get install -yq --no-install-recommends \
    btrfs-tools \
    ca-certificates && \
  apt-get clean && \
  rm -rf /var/lib/apt
RUN \
  curl -sSL https://get.docker.com/builds/Linux/x86_64/docker-1.8.2 > /bin/docker && \
  chmod +x /bin/docker
ENV GO15VENDOREXPERIMENT 1
RUN mkdir -p /go/src/github.com/libopenstorage/openstorage
ADD . /go/src/github.com/libopenstorage/openstorage/
WORKDIR /go/src/github.com/libopenstorage/openstorage
