apiVersion: v1
kind: ServiceAccount
metadata:
  name: osd-csi-account
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: osd-csi-role
rules:
- apiGroups: ["extensions"]
  resources: ["podsecuritypolicies"]
  resourceNames: ["privileged"]
  verbs: ["use"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims/status"]
  verbs: ["update", "patch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["volumeattachments"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["volumesnapshots", "volumesnapshotcontents", "volumesnapshotclasses", "volumesnapshots/status"]
  verbs: ["create", "get", "list", "watch", "update", "delete"]
- apiGroups: ["storage.k8s.io"]
  resources: ["csinodes"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["csi.storage.k8s.io"]
  resources: ["csidrivers"]
  verbs: ["create", "delete"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: osd-csi-role-binding
subjects:
- kind: ServiceAccount
  name: osd-csi-account
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: osd-csi-role
  apiGroup: rbac.authorization.k8s.io
---
kind: Service
apiVersion: v1
metadata:
  name: osd-csi-service
  namespace: kube-system
spec:
  clusterIP: None
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: osd-csi-ext
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osd-csi-driver
  template:
    metadata:
      labels:
        app: osd-csi-driver
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: px/enabled
                operator: NotIn
                values:
                - "false"
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
      serviceAccount: osd-csi-account
      containers:
        - name: csi-external-provisioner
          imagePullPolicy: Always
          image: quay.io/openstorage/csi-provisioner:v1.4.0-1
          args:
            - "--v=3"
            - "--provisioner=osd.openstorage.org"
            - "--csi-address=$(ADDRESS)"
            - "--enable-leader-election"
            - "--leader-election-type=leases"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          securityContext:
            privileged: true
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-snapshotter
          imagePullPolicy: Always
          image: quay.io/openstorage/csi-snapshotter:v1.2.2-1
          args:
            - "--v=3"
            - "--csi-address=$(ADDRESS)"
            - "--snapshotter=osd.openstorage.org"
            - "--leader-election=true"
            - "--leader-election-type=leases"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          securityContext:
            privileged: true
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-resizer
          imagePullPolicy: Always
          image: quay.io/k8scsi/csi-resizer:v0.3.0
          args:
            - "--v=3"
            - "--csi-address=$(ADDRESS)"
            - "--leader-election=true"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          securityContext:
            privileged: true
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/osd.openstorage.org
            type: DirectoryOrCreate
---
apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: osd.openstorage.org
spec:
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
  - Persistent
  - Ephemeral
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: openstorage
  namespace: kube-system
  labels:
    name: openstorage
spec:
  selector:
    matchLabels:
      name: openstorage
  minReadySeconds: 0
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: openstorage
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: px/enabled
                operator: NotIn
                values:
                - "false"
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
      hostNetwork: true
      hostPID: false
      containers:
        - name: osd
          image: quay.io/openstorage/osd-dev-base:1.14
          imagePullPolicy: Never # Manually loaded into KinD (see setup script)
          args:
              ["-d","--driver=name=fake", "--csidrivername","osd.openstorage.org"]
          env:
            - name: "CSI_ENDPOINT"
              value: "/var/lib/kubelet/plugins/osd.openstorage.org/csi.sock"
          securityContext:
            privileged: true
          volumeMounts:
          - name: csi-driver-path
            mountPath: /var/lib/kubelet/plugins/osd.openstorage.org
          - name: csi-kubelet-path
            mountPath: /var/lib/kubelet
        - name: csi-node-driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/osd.openstorage.org/csi.sock"
          imagePullPolicy: Always
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
          volumeMounts:
            - name: csi-driver-path
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
      restartPolicy: Always
      serviceAccountName: osd-csi-account
      volumes:
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: DirectoryOrCreate
        - name: csi-kubelet-path
          hostPath:
            path: /var/lib/kubelet
            type: DirectoryOrCreate
        - name: csi-driver-path
          hostPath:
            path: /var/lib/kubelet/plugins/osd.openstorage.org
            type: DirectoryOrCreate
