# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: api.proto for package 'openstorage.api'

require 'grpc'
require 'api_pb'

module Openstorage
  module Api
    module OpenStorageCluster
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'openstorage.api.OpenStorageCluster'

        # Enumerate lists all the nodes in the cluster.
        rpc :Enumerate, ClusterEnumerateRequest, ClusterEnumerateResponse
        # Inspect the node given a UUID.
        rpc :Inspect, ClusterInspectRequest, ClusterInspectResponse
        # Get a list of alerts from the storage cluster
        rpc :AlertEnumerate, ClusterAlertEnumerateRequest, ClusterAlertEnumerateResponse
        # Clear the alert for a given resource
        rpc :AlertClear, ClusterAlertClearRequest, ClusterAlertClearResponse
        # Erases an alert for a given resource
        rpc :AlertErase, ClusterAlertEraseRequest, ClusterAlertEraseResponse
      end

      Stub = Service.rpc_stub_class
    end
    module OpenStorageVolume
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'openstorage.api.OpenStorageVolume'

        # Creates a new volume
        rpc :Create, OpenStorageVolumeCreateRequest, OpenStorageVolumeCreateResponse
        # CreateFromVolumeID creates a new volume cloned from an existing volume
        rpc :CreateFromVolumeID, VolumeCreateFromVolumeIDRequest, VolumeCreateFromVolumeIDResponse
        # Delete a volume
        rpc :Delete, VolumeDeleteRequest, VolumeDeleteResponse
        # Get information on a volume
        rpc :Inspect, VolumeInspectRequest, VolumeInspectResponse
        # Get a list of volumes
        rpc :Enumerate, VolumeEnumerateRequest, VolumeEnumerateResponse
        # Create a snapshot of a volume. This creates an immutable (read-only),
        # point-in-time snapshot of a volume.
        rpc :SnapshotCreate, VolumeSnapshotCreateRequest, VolumeSnapshotCreateResponse
        # Restores a volume to a specified snapshot
        rpc :SnapshotRestore, VolumeSnapshotRestoreRequest, VolumeSnapshotRestoreResponse
        # List the number of snapshots for a specific volume
        rpc :SnapshotEnumerate, VolumeSnapshotEnumerateRequest, VolumeSnapshotEnumerateResponse
        # Attach device to host                                                      
        rpc :Attach, VolumeAttachRequest, VolumeAttachResponse
        # Detaches the volume from the node.
        rpc :Detach, VolumeDetachRequest, VolumeDetachResponse
        # Attaches the volume to a node.
        rpc :Mount, VolumeMountRequest, VolumeMountResponse
        # Unmount volume at specified path                                           
        rpc :Unmount, VolumeUnmountRequest, VolumeUnmountResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
