# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: api.proto for package 'openstorage.api'

require 'grpc'
require 'api_pb'

module Openstorage
  module Api
    module OpenStorageCluster
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'openstorage.api.OpenStorageCluster'

        # Enumerate lists all the nodes in the cluster.
        rpc :Enumerate, ClusterEnumerateRequest, ClusterEnumerateResponse
        # Inspect the node given a UUID.
        rpc :Inspect, ClusterInspectRequest, ClusterInspectResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
