// Code generated by protoc-gen-go.
// source: pkg/flexvolume/flexvolume.proto
// DO NOT EDIT!

package flexvolume

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gengo/grpc-gateway/third_party/googleapis/google/api"
import google_protobuf1 "go.pedge.io/pb/go/google/protobuf"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type AttachRequest struct {
	JsonOptions map[string]string `protobuf:"bytes,1,rep,name=json_options" json:"json_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *AttachRequest) Reset()                    { *m = AttachRequest{} }
func (m *AttachRequest) String() string            { return proto.CompactTextString(m) }
func (*AttachRequest) ProtoMessage()               {}
func (*AttachRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AttachRequest) GetJsonOptions() map[string]string {
	if m != nil {
		return m.JsonOptions
	}
	return nil
}

type DetachRequest struct {
	MountDevice string `protobuf:"bytes,1,opt,name=mount_device" json:"mount_device,omitempty"`
}

func (m *DetachRequest) Reset()                    { *m = DetachRequest{} }
func (m *DetachRequest) String() string            { return proto.CompactTextString(m) }
func (*DetachRequest) ProtoMessage()               {}
func (*DetachRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type MountRequest struct {
	TargetMountDir string            `protobuf:"bytes,1,opt,name=target_mount_dir" json:"target_mount_dir,omitempty"`
	MountDevice    string            `protobuf:"bytes,2,opt,name=mount_device" json:"mount_device,omitempty"`
	JsonOptions    map[string]string `protobuf:"bytes,3,rep,name=json_options" json:"json_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *MountRequest) Reset()                    { *m = MountRequest{} }
func (m *MountRequest) String() string            { return proto.CompactTextString(m) }
func (*MountRequest) ProtoMessage()               {}
func (*MountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MountRequest) GetJsonOptions() map[string]string {
	if m != nil {
		return m.JsonOptions
	}
	return nil
}

type UnmountRequest struct {
	MountDir string `protobuf:"bytes,1,opt,name=mount_dir" json:"mount_dir,omitempty"`
}

func (m *UnmountRequest) Reset()                    { *m = UnmountRequest{} }
func (m *UnmountRequest) String() string            { return proto.CompactTextString(m) }
func (*UnmountRequest) ProtoMessage()               {}
func (*UnmountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*AttachRequest)(nil), "flexvolume.AttachRequest")
	proto.RegisterType((*DetachRequest)(nil), "flexvolume.DetachRequest")
	proto.RegisterType((*MountRequest)(nil), "flexvolume.MountRequest")
	proto.RegisterType((*UnmountRequest)(nil), "flexvolume.UnmountRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for API service

type APIClient interface {
	Init(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	Attach(ctx context.Context, in *AttachRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	Detach(ctx context.Context, in *DetachRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	Mount(ctx context.Context, in *MountRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	Unmount(ctx context.Context, in *UnmountRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) Init(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/flexvolume.API/Init", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) Attach(ctx context.Context, in *AttachRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/flexvolume.API/Attach", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) Detach(ctx context.Context, in *DetachRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/flexvolume.API/Detach", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) Mount(ctx context.Context, in *MountRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/flexvolume.API/Mount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) Unmount(ctx context.Context, in *UnmountRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/flexvolume.API/Unmount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for API service

type APIServer interface {
	Init(context.Context, *google_protobuf1.Empty) (*google_protobuf1.Empty, error)
	Attach(context.Context, *AttachRequest) (*google_protobuf1.Empty, error)
	Detach(context.Context, *DetachRequest) (*google_protobuf1.Empty, error)
	Mount(context.Context, *MountRequest) (*google_protobuf1.Empty, error)
	Unmount(context.Context, *UnmountRequest) (*google_protobuf1.Empty, error)
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(APIServer).Init(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _API_Attach_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(AttachRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(APIServer).Attach(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _API_Detach_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(DetachRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(APIServer).Detach(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _API_Mount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(MountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(APIServer).Mount(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _API_Unmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(UnmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(APIServer).Unmount(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "flexvolume.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _API_Init_Handler,
		},
		{
			MethodName: "Attach",
			Handler:    _API_Attach_Handler,
		},
		{
			MethodName: "Detach",
			Handler:    _API_Detach_Handler,
		},
		{
			MethodName: "Mount",
			Handler:    _API_Mount_Handler,
		},
		{
			MethodName: "Unmount",
			Handler:    _API_Unmount_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x91, 0xd1, 0x6a, 0xdb, 0x30,
	0x14, 0x86, 0x71, 0xbc, 0x24, 0xcb, 0x89, 0x3d, 0x12, 0x6d, 0x0c, 0xcf, 0x1b, 0x6c, 0x68, 0x0c,
	0xb2, 0x5c, 0x58, 0x90, 0xdd, 0x8c, 0xdc, 0x6c, 0x81, 0x05, 0x96, 0xd2, 0x92, 0x12, 0xe8, 0x75,
	0x70, 0x12, 0xc5, 0x75, 0x63, 0x4b, 0xae, 0x23, 0x87, 0xe6, 0xb6, 0xd0, 0x27, 0xc8, 0xa3, 0xf4,
	0x51, 0xfa, 0x0a, 0x7d, 0x90, 0xc6, 0xb2, 0x4d, 0x6d, 0x83, 0xa1, 0x17, 0xbd, 0x93, 0x8e, 0xfe,
	0xf3, 0xe9, 0x9c, 0xff, 0x87, 0xaf, 0xc1, 0xc6, 0x21, 0x6b, 0x8f, 0xde, 0xec, 0xb8, 0x17, 0xf9,
	0x34, 0x77, 0xb4, 0x82, 0x90, 0x0b, 0x8e, 0xe0, 0xb9, 0x62, 0x7e, 0x71, 0x38, 0x77, 0x3c, 0x4a,
	0xec, 0xc0, 0x25, 0x36, 0x63, 0x5c, 0xd8, 0xc2, 0xe5, 0x6c, 0x9b, 0x28, 0xcd, 0xcf, 0xe9, 0xab,
	0xbc, 0x2d, 0xa2, 0x35, 0xa1, 0x7e, 0x20, 0xf6, 0xc9, 0x23, 0xbe, 0x53, 0x40, 0x1f, 0x09, 0x61,
	0x2f, 0x2f, 0x67, 0xf4, 0x3a, 0xa2, 0x5b, 0x81, 0xfe, 0x82, 0x76, 0xb5, 0xe5, 0x6c, 0xce, 0x03,
	0x09, 0x31, 0x94, 0x6f, 0x6a, 0xaf, 0x3d, 0xe8, 0x5b, 0xb9, 0x09, 0x0a, 0x0d, 0xd6, 0xc9, 0x51,
	0x3d, 0x4d, 0xc4, 0x63, 0x26, 0xc2, 0xbd, 0x39, 0x80, 0x4e, 0xb9, 0x86, 0xda, 0xa0, 0x6e, 0xe8,
	0xfe, 0x08, 0x53, 0x7a, 0x2d, 0xa4, 0x43, 0x7d, 0x67, 0x7b, 0x11, 0x35, 0x6a, 0xf1, 0x75, 0x58,
	0xfb, 0xad, 0xe0, 0x1f, 0xa0, 0xff, 0xa3, 0xf9, 0x31, 0x3e, 0x80, 0xe6, 0xf3, 0x88, 0x89, 0xf9,
	0x8a, 0xee, 0xdc, 0x25, 0x4d, 0x3a, 0xf1, 0xbd, 0x02, 0xda, 0x59, 0x5c, 0xce, 0x64, 0x06, 0x74,
	0x84, 0x1d, 0x3a, 0x54, 0xcc, 0x53, 0xb5, 0x1b, 0xa6, 0x9f, 0x94, 0x01, 0xf2, 0x2f, 0xf4, 0xa7,
	0xb4, 0x9d, 0x2a, 0xb7, 0xfb, 0x99, 0xdf, 0x2e, 0xcf, 0x7f, 0x9d, 0xe5, 0xbe, 0xc3, 0xbb, 0x0b,
	0xe6, 0xe7, 0xc7, 0xee, 0x42, 0xab, 0x34, 0xef, 0xe0, 0xa0, 0x82, 0x3a, 0x3a, 0x9f, 0xa0, 0xff,
	0xf0, 0x66, 0xc2, 0x5c, 0x81, 0x3e, 0x5a, 0x49, 0x6e, 0x56, 0x96, 0x9b, 0x35, 0x8e, 0x73, 0x33,
	0x2b, 0xea, 0xb8, 0x73, 0xfb, 0xf0, 0x78, 0xa8, 0x01, 0xae, 0x13, 0xf7, 0xd8, 0x3e, 0x54, 0xfa,
	0x68, 0x0a, 0x8d, 0x24, 0x29, 0xf4, 0xa9, 0x32, 0xbd, 0x4a, 0x1c, 0x92, 0x38, 0x0d, 0x37, 0x89,
	0x2d, 0xf5, 0x29, 0x30, 0x09, 0xa9, 0x08, 0x2c, 0x04, 0xf7, 0x02, 0xe0, 0x8a, 0x66, 0xc0, 0x53,
	0xa8, 0x4b, 0xb7, 0x91, 0x51, 0x15, 0x40, 0x25, 0xae, 0x2b, 0x71, 0x6d, 0xdc, 0x20, 0xd2, 0xc8,
	0x98, 0x36, 0x83, 0x66, 0x6a, 0x33, 0x32, 0xf3, 0xbc, 0xa2, 0xf7, 0x95, 0xc4, 0xf7, 0x92, 0xa8,
	0xe3, 0xb7, 0x24, 0x62, 0x19, 0x73, 0xd1, 0x90, 0xa2, 0x5f, 0x4f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x77, 0xb5, 0xfe, 0x43, 0x90, 0x03, 0x00, 0x00,
}
