// Code generated by protoc-gen-go.
// source: api/api.proto
// DO NOT EDIT!

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "go.pedge.io/pb/go/google/protobuf"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Status int32

const (
	Status_STATUS_NONE          Status = 0
	Status_STATUS_INIT          Status = 1
	Status_STATUS_OK            Status = 2
	Status_STATUS_OFFLINE       Status = 3
	Status_STATUS_ERROR         Status = 4
	Status_STATUS_NOT_IN_QUORUM Status = 5
	Status_STATUS_DECOMMISSION  Status = 6
	Status_STATUS_MAINTENANCE   Status = 7
)

var Status_name = map[int32]string{
	0: "STATUS_NONE",
	1: "STATUS_INIT",
	2: "STATUS_OK",
	3: "STATUS_OFFLINE",
	4: "STATUS_ERROR",
	5: "STATUS_NOT_IN_QUORUM",
	6: "STATUS_DECOMMISSION",
	7: "STATUS_MAINTENANCE",
}
var Status_value = map[string]int32{
	"STATUS_NONE":          0,
	"STATUS_INIT":          1,
	"STATUS_OK":            2,
	"STATUS_OFFLINE":       3,
	"STATUS_ERROR":         4,
	"STATUS_NOT_IN_QUORUM": 5,
	"STATUS_DECOMMISSION":  6,
	"STATUS_MAINTENANCE":   7,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}
func (Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type DriverType int32

const (
	DriverType_DRIVER_TYPE_NONE      DriverType = 0
	DriverType_DRIVER_TYPE_FILE      DriverType = 1
	DriverType_DRIVER_TYPE_BLOCK     DriverType = 2
	DriverType_DRIVER_TYPE_OBJECT    DriverType = 3
	DriverType_DRIVER_TYPE_CLUSTERED DriverType = 4
	DriverType_DRIVER_TYPE_GRAPH     DriverType = 5
)

var DriverType_name = map[int32]string{
	0: "DRIVER_TYPE_NONE",
	1: "DRIVER_TYPE_FILE",
	2: "DRIVER_TYPE_BLOCK",
	3: "DRIVER_TYPE_OBJECT",
	4: "DRIVER_TYPE_CLUSTERED",
	5: "DRIVER_TYPE_GRAPH",
}
var DriverType_value = map[string]int32{
	"DRIVER_TYPE_NONE":      0,
	"DRIVER_TYPE_FILE":      1,
	"DRIVER_TYPE_BLOCK":     2,
	"DRIVER_TYPE_OBJECT":    3,
	"DRIVER_TYPE_CLUSTERED": 4,
	"DRIVER_TYPE_GRAPH":     5,
}

func (x DriverType) String() string {
	return proto.EnumName(DriverType_name, int32(x))
}
func (DriverType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type FSType int32

const (
	FSType_FS_TYPE_NONE  FSType = 0
	FSType_FS_TYPE_BTRFS FSType = 1
	FSType_FS_TYPE_EXT4  FSType = 2
	FSType_FS_TYPE_FUSE  FSType = 3
	FSType_FS_TYPE_NFS   FSType = 4
	FSType_FS_TYPE_VFS   FSType = 5
	FSType_FS_TYPE_XFS   FSType = 6
	FSType_FS_TYPE_ZFS   FSType = 7
)

var FSType_name = map[int32]string{
	0: "FS_TYPE_NONE",
	1: "FS_TYPE_BTRFS",
	2: "FS_TYPE_EXT4",
	3: "FS_TYPE_FUSE",
	4: "FS_TYPE_NFS",
	5: "FS_TYPE_VFS",
	6: "FS_TYPE_XFS",
	7: "FS_TYPE_ZFS",
}
var FSType_value = map[string]int32{
	"FS_TYPE_NONE":  0,
	"FS_TYPE_BTRFS": 1,
	"FS_TYPE_EXT4":  2,
	"FS_TYPE_FUSE":  3,
	"FS_TYPE_NFS":   4,
	"FS_TYPE_VFS":   5,
	"FS_TYPE_XFS":   6,
	"FS_TYPE_ZFS":   7,
}

func (x FSType) String() string {
	return proto.EnumName(FSType_name, int32(x))
}
func (FSType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type GraphDriverChangeType int32

const (
	GraphDriverChangeType_GRAPH_DRIVER_CHANGE_TYPE_NONE     GraphDriverChangeType = 0
	GraphDriverChangeType_GRAPH_DRIVER_CHANGE_TYPE_MODIFIED GraphDriverChangeType = 1
	GraphDriverChangeType_GRAPH_DRIVER_CHANGE_TYPE_ADDED    GraphDriverChangeType = 2
	GraphDriverChangeType_GRAPH_DRIVER_CHANGE_TYPE_DELETED  GraphDriverChangeType = 3
)

var GraphDriverChangeType_name = map[int32]string{
	0: "GRAPH_DRIVER_CHANGE_TYPE_NONE",
	1: "GRAPH_DRIVER_CHANGE_TYPE_MODIFIED",
	2: "GRAPH_DRIVER_CHANGE_TYPE_ADDED",
	3: "GRAPH_DRIVER_CHANGE_TYPE_DELETED",
}
var GraphDriverChangeType_value = map[string]int32{
	"GRAPH_DRIVER_CHANGE_TYPE_NONE":     0,
	"GRAPH_DRIVER_CHANGE_TYPE_MODIFIED": 1,
	"GRAPH_DRIVER_CHANGE_TYPE_ADDED":    2,
	"GRAPH_DRIVER_CHANGE_TYPE_DELETED":  3,
}

func (x GraphDriverChangeType) String() string {
	return proto.EnumName(GraphDriverChangeType_name, int32(x))
}
func (GraphDriverChangeType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type SeverityType int32

const (
	SeverityType_SEVERITY_TYPE_NONE    SeverityType = 0
	SeverityType_SEVERITY_TYPE_ALARM   SeverityType = 1
	SeverityType_SEVERITY_TYPE_WARNING SeverityType = 2
	SeverityType_SEVERITY_TYPE_NOTIFY  SeverityType = 3
)

var SeverityType_name = map[int32]string{
	0: "SEVERITY_TYPE_NONE",
	1: "SEVERITY_TYPE_ALARM",
	2: "SEVERITY_TYPE_WARNING",
	3: "SEVERITY_TYPE_NOTIFY",
}
var SeverityType_value = map[string]int32{
	"SEVERITY_TYPE_NONE":    0,
	"SEVERITY_TYPE_ALARM":   1,
	"SEVERITY_TYPE_WARNING": 2,
	"SEVERITY_TYPE_NOTIFY":  3,
}

func (x SeverityType) String() string {
	return proto.EnumName(SeverityType_name, int32(x))
}
func (SeverityType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ResourceType int32

const (
	ResourceType_RESOURCE_TYPE_NONE    ResourceType = 0
	ResourceType_RESOURCE_TYPE_VOLUME  ResourceType = 1
	ResourceType_RESOURCE_TYPE_NODE    ResourceType = 2
	ResourceType_RESOURCE_TYPE_CLUSTER ResourceType = 3
	ResourceType_RESOURCE_TYPE_DRIVE   ResourceType = 4
)

var ResourceType_name = map[int32]string{
	0: "RESOURCE_TYPE_NONE",
	1: "RESOURCE_TYPE_VOLUME",
	2: "RESOURCE_TYPE_NODE",
	3: "RESOURCE_TYPE_CLUSTER",
	4: "RESOURCE_TYPE_DRIVE",
}
var ResourceType_value = map[string]int32{
	"RESOURCE_TYPE_NONE":    0,
	"RESOURCE_TYPE_VOLUME":  1,
	"RESOURCE_TYPE_NODE":    2,
	"RESOURCE_TYPE_CLUSTER": 3,
	"RESOURCE_TYPE_DRIVE":   4,
}

func (x ResourceType) String() string {
	return proto.EnumName(ResourceType_name, int32(x))
}
func (ResourceType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type AlertActionType int32

const (
	AlertActionType_ALERT_ACTION_TYPE_NONE   AlertActionType = 0
	AlertActionType_ALERT_ACTION_TYPE_DELETE AlertActionType = 1
	AlertActionType_ALERT_ACTION_TYPE_CREATE AlertActionType = 2
	AlertActionType_ALERT_ACTION_TYPE_UPDATE AlertActionType = 3
)

var AlertActionType_name = map[int32]string{
	0: "ALERT_ACTION_TYPE_NONE",
	1: "ALERT_ACTION_TYPE_DELETE",
	2: "ALERT_ACTION_TYPE_CREATE",
	3: "ALERT_ACTION_TYPE_UPDATE",
}
var AlertActionType_value = map[string]int32{
	"ALERT_ACTION_TYPE_NONE":   0,
	"ALERT_ACTION_TYPE_DELETE": 1,
	"ALERT_ACTION_TYPE_CREATE": 2,
	"ALERT_ACTION_TYPE_UPDATE": 3,
}

func (x AlertActionType) String() string {
	return proto.EnumName(AlertActionType_name, int32(x))
}
func (AlertActionType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type VolumeActionParam int32

const (
	VolumeActionParam_VOLUME_ACTION_PARAM_NONE VolumeActionParam = 0
	// Maps to the boolean value false
	VolumeActionParam_VOLUME_ACTION_PARAM_OFF VolumeActionParam = 1
	// Maps to the boolean value true.
	VolumeActionParam_VOLUME_ACTION_PARAM_ON VolumeActionParam = 2
)

var VolumeActionParam_name = map[int32]string{
	0: "VOLUME_ACTION_PARAM_NONE",
	1: "VOLUME_ACTION_PARAM_OFF",
	2: "VOLUME_ACTION_PARAM_ON",
}
var VolumeActionParam_value = map[string]int32{
	"VOLUME_ACTION_PARAM_NONE": 0,
	"VOLUME_ACTION_PARAM_OFF":  1,
	"VOLUME_ACTION_PARAM_ON":   2,
}

func (x VolumeActionParam) String() string {
	return proto.EnumName(VolumeActionParam_name, int32(x))
}
func (VolumeActionParam) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type CosType int32

const (
	CosType_COS_TYPE_NONE   CosType = 0
	CosType_COS_TYPE_LOW    CosType = 1
	CosType_COS_TYPE_MEDIUM CosType = 2
	CosType_COS_TYPE_HIGH   CosType = 3
)

var CosType_name = map[int32]string{
	0: "COS_TYPE_NONE",
	1: "COS_TYPE_LOW",
	2: "COS_TYPE_MEDIUM",
	3: "COS_TYPE_HIGH",
}
var CosType_value = map[string]int32{
	"COS_TYPE_NONE":   0,
	"COS_TYPE_LOW":    1,
	"COS_TYPE_MEDIUM": 2,
	"COS_TYPE_HIGH":   3,
}

func (x CosType) String() string {
	return proto.EnumName(CosType_name, int32(x))
}
func (CosType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

// VolumeState represents the state of a volume.
type VolumeState int32

const (
	VolumeState_VOLUME_STATE_NONE VolumeState = 0
	// Volume is transitioning to new state
	VolumeState_VOLUME_STATE_PENDING VolumeState = 1
	// Volume is ready to be assigned to a container
	VolumeState_VOLUME_STATE_AVAILABLE VolumeState = 2
	// Volume is attached to container
	VolumeState_VOLUME_STATE_ATTACHED VolumeState = 3
	// Volume is detached but associated with a container
	VolumeState_VOLUME_STATE_DETACHED VolumeState = 4
	// Volume detach is in progress
	VolumeState_VOLUME_STATE_DETATCHING VolumeState = 5
	// Volume is in error state
	VolumeState_VOLUME_STATE_ERROR VolumeState = 6
	// Volume is deleted, it will remain in this state
	// while resources are asynchronously reclaimed
	VolumeState_VOLUME_STATE_DELETED VolumeState = 7
)

var VolumeState_name = map[int32]string{
	0: "VOLUME_STATE_NONE",
	1: "VOLUME_STATE_PENDING",
	2: "VOLUME_STATE_AVAILABLE",
	3: "VOLUME_STATE_ATTACHED",
	4: "VOLUME_STATE_DETACHED",
	5: "VOLUME_STATE_DETATCHING",
	6: "VOLUME_STATE_ERROR",
	7: "VOLUME_STATE_DELETED",
}
var VolumeState_value = map[string]int32{
	"VOLUME_STATE_NONE":       0,
	"VOLUME_STATE_PENDING":    1,
	"VOLUME_STATE_AVAILABLE":  2,
	"VOLUME_STATE_ATTACHED":   3,
	"VOLUME_STATE_DETACHED":   4,
	"VOLUME_STATE_DETATCHING": 5,
	"VOLUME_STATE_ERROR":      6,
	"VOLUME_STATE_DELETED":    7,
}

func (x VolumeState) String() string {
	return proto.EnumName(VolumeState_name, int32(x))
}
func (VolumeState) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

// VolumeStatus represents a health status for a volume.
type VolumeStatus int32

const (
	VolumeStatus_VOLUME_STATUS_NONE VolumeStatus = 0
	// Volume is not present
	VolumeStatus_VOLUME_STATUS_NOT_PRESENT VolumeStatus = 1
	// Volume is healthy
	VolumeStatus_VOLUME_STATUS_UP VolumeStatus = 2
	// Volume is in fail mode
	VolumeStatus_VOLUME_STATUS_DOWN VolumeStatus = 3
	// Volume is up but with degraded performance
	// In a RAID group, this may indicate a problem with one or more drives
	VolumeStatus_VOLUME_STATUS_DEGRADED VolumeStatus = 4
)

var VolumeStatus_name = map[int32]string{
	0: "VOLUME_STATUS_NONE",
	1: "VOLUME_STATUS_NOT_PRESENT",
	2: "VOLUME_STATUS_UP",
	3: "VOLUME_STATUS_DOWN",
	4: "VOLUME_STATUS_DEGRADED",
}
var VolumeStatus_value = map[string]int32{
	"VOLUME_STATUS_NONE":        0,
	"VOLUME_STATUS_NOT_PRESENT": 1,
	"VOLUME_STATUS_UP":          2,
	"VOLUME_STATUS_DOWN":        3,
	"VOLUME_STATUS_DEGRADED":    4,
}

func (x VolumeStatus) String() string {
	return proto.EnumName(VolumeStatus_name, int32(x))
}
func (VolumeStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type StorageMedium int32

const (
	// Magnetic spinning disk.
	StorageMedium_STORAGE_MEDIUM_MAGNETIC StorageMedium = 0
	// SSD disk
	StorageMedium_STORAGE_MEDIUM_SSD StorageMedium = 1
	// NVME disk
	StorageMedium_STORAGE_MEDIUM_NVME StorageMedium = 2
)

var StorageMedium_name = map[int32]string{
	0: "STORAGE_MEDIUM_MAGNETIC",
	1: "STORAGE_MEDIUM_SSD",
	2: "STORAGE_MEDIUM_NVME",
}
var StorageMedium_value = map[string]int32{
	"STORAGE_MEDIUM_MAGNETIC": 0,
	"STORAGE_MEDIUM_SSD":      1,
	"STORAGE_MEDIUM_NVME":     2,
}

func (x StorageMedium) String() string {
	return proto.EnumName(StorageMedium_name, int32(x))
}
func (StorageMedium) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type ClusterNotify int32

const (
	// Node is down
	ClusterNotify_CLUSTER_NOTIFY_DOWN ClusterNotify = 0
)

var ClusterNotify_name = map[int32]string{
	0: "CLUSTER_NOTIFY_DOWN",
}
var ClusterNotify_value = map[string]int32{
	"CLUSTER_NOTIFY_DOWN": 0,
}

func (x ClusterNotify) String() string {
	return proto.EnumName(ClusterNotify_name, int32(x))
}
func (ClusterNotify) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

// StorageResource groups properties of a storage device.
type StorageResource struct {
	// Id is the LUN identifier.
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// Path device path for this storage resource.
	Path string `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	// Storage medium.
	Medium StorageMedium `protobuf:"varint,3,opt,name=medium,enum=openstorage.api.StorageMedium" json:"medium,omitempty"`
	// True if this device is online.
	Online bool `protobuf:"varint,4,opt,name=online" json:"online,omitempty"`
	// IOPS
	Iops uint64 `protobuf:"varint,5,opt,name=iops" json:"iops,omitempty"`
	// SeqWrite
	SeqWrite float64 `protobuf:"fixed64,6,opt,name=seq_write,json=seqWrite" json:"seq_write,omitempty"`
	// SeqRead
	SeqRead float64 `protobuf:"fixed64,7,opt,name=seq_read,json=seqRead" json:"seq_read,omitempty"`
	// RandRW
	RandRW float64 `protobuf:"fixed64,8,opt,name=randRW" json:"randRW,omitempty"`
	// Total size in bytes.
	Size uint64 `protobuf:"varint,9,opt,name=size" json:"size,omitempty"`
	// Physical Bytes used.
	Used uint64 `protobuf:"varint,10,opt,name=used" json:"used,omitempty"`
	// True if this device is rotational.
	RotationSpeed string `protobuf:"bytes,11,opt,name=rotation_speed,json=rotationSpeed" json:"rotation_speed,omitempty"`
	// Timestamp of last time this device was scanned.
	LastScan *google_protobuf.Timestamp `protobuf:"bytes,12,opt,name=last_scan,json=lastScan" json:"last_scan,omitempty"`
}

func (m *StorageResource) Reset()                    { *m = StorageResource{} }
func (m *StorageResource) String() string            { return proto.CompactTextString(m) }
func (*StorageResource) ProtoMessage()               {}
func (*StorageResource) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StorageResource) GetLastScan() *google_protobuf.Timestamp {
	if m != nil {
		return m.LastScan
	}
	return nil
}

// VolumeLocator is a structure that is attached to a volume
// and is used to carry opaque metadata.
type VolumeLocator struct {
	// User friendly identifier
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// A set of name-value pairs that acts as search filters
	VolumeLabels map[string]string `protobuf:"bytes,2,rep,name=volume_labels,json=volumeLabels" json:"volume_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *VolumeLocator) Reset()                    { *m = VolumeLocator{} }
func (m *VolumeLocator) String() string            { return proto.CompactTextString(m) }
func (*VolumeLocator) ProtoMessage()               {}
func (*VolumeLocator) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *VolumeLocator) GetVolumeLabels() map[string]string {
	if m != nil {
		return m.VolumeLabels
	}
	return nil
}

type Source struct {
	// A volume id, if specified will create a clone of the parent.
	Parent string `protobuf:"bytes,1,opt,name=parent" json:"parent,omitempty"`
	// Seed will seed the volume from the specified URI
	// Any additional config for the source comes from the labels in the spec
	Seed string `protobuf:"bytes,2,opt,name=seed" json:"seed,omitempty"`
}

func (m *Source) Reset()                    { *m = Source{} }
func (m *Source) String() string            { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()               {}
func (*Source) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// VolumeSpec has the properties needed to create a volume.
type VolumeSpec struct {
	// Ephemeral storage
	Ephemeral bool `protobuf:"varint,1,opt,name=ephemeral" json:"ephemeral,omitempty"`
	// Thin provisioned volume size in bytes
	Size uint64 `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	// Format disk with this FSType
	Format FSType `protobuf:"varint,3,opt,name=format,enum=openstorage.api.FSType" json:"format,omitempty"`
	// Block size for filesystem
	BlockSize int64 `protobuf:"varint,4,opt,name=block_size,json=blockSize" json:"block_size,omitempty"`
	// Specifies the number of nodes that are
	// allowed to fail, and yet data is available
	// A value of 0 implies that data is not erasure coded,
	// a failure of a node will lead to data loss
	HaLevel int64 `protobuf:"varint,5,opt,name=ha_level,json=haLevel" json:"ha_level,omitempty"`
	// The COS, 1 to 9
	Cos uint32 `protobuf:"varint,6,opt,name=cos" json:"cos,omitempty"`
	// Perform dedupe on this disk
	Dedupe bool `protobuf:"varint,7,opt,name=dedupe" json:"dedupe,omitempty"`
	// SnapshotInterval in minutes, set to 0 to disable snapshots
	SnapshotInterval uint32 `protobuf:"varint,8,opt,name=snapshot_interval,json=snapshotInterval" json:"snapshot_interval,omitempty"`
	// Volume configuration labels
	VolumeLabels map[string]string `protobuf:"bytes,9,rep,name=volume_labels,json=volumeLabels" json:"volume_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Shared is true if this volume can be remotely accessed.
	Shared bool `protobuf:"varint,10,opt,name=shared" json:"shared,omitempty"`
	// ReplicaSet is the desired replicaSet the volume want to be placed.
	ReplicaSet *ReplicaSet `protobuf:"bytes,11,opt,name=replica_set,json=replicaSet" json:"replica_set,omitempty"`
	// Specifies the number of parts the volume can be aggregated from.
	AggregationLevel uint32 `protobuf:"varint,12,opt,name=aggregation_level,json=aggregationLevel" json:"aggregation_level,omitempty"`
	// Encrypted is true if this volume will be cryptographically secured.
	Encrypted bool `protobuf:"varint,13,opt,name=encrypted" json:"encrypted,omitempty"`
	// User passphrase if this is an encrypted volume
	Passphrase string `protobuf:"bytes,14,opt,name=passphrase" json:"passphrase,omitempty"`
}

func (m *VolumeSpec) Reset()                    { *m = VolumeSpec{} }
func (m *VolumeSpec) String() string            { return proto.CompactTextString(m) }
func (*VolumeSpec) ProtoMessage()               {}
func (*VolumeSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *VolumeSpec) GetVolumeLabels() map[string]string {
	if m != nil {
		return m.VolumeLabels
	}
	return nil
}

func (m *VolumeSpec) GetReplicaSet() *ReplicaSet {
	if m != nil {
		return m.ReplicaSet
	}
	return nil
}

// Set of machine IDs (nodes) to which part of this volume is erasure coded - for clustered storage arrays
type ReplicaSet struct {
	Nodes []string `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *ReplicaSet) Reset()                    { *m = ReplicaSet{} }
func (m *ReplicaSet) String() string            { return proto.CompactTextString(m) }
func (*ReplicaSet) ProtoMessage()               {}
func (*ReplicaSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

// List of name value mapping of driver specific runtime information.
type RuntimeStateMap struct {
	RuntimeState map[string]string `protobuf:"bytes,1,rep,name=runtime_state,json=runtimeState" json:"runtime_state,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *RuntimeStateMap) Reset()                    { *m = RuntimeStateMap{} }
func (m *RuntimeStateMap) String() string            { return proto.CompactTextString(m) }
func (*RuntimeStateMap) ProtoMessage()               {}
func (*RuntimeStateMap) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RuntimeStateMap) GetRuntimeState() map[string]string {
	if m != nil {
		return m.RuntimeState
	}
	return nil
}

// Volume represents a live, created volume.
type Volume struct {
	// Self referential volume ID
	Id       string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Source   *Source `protobuf:"bytes,2,opt,name=source" json:"source,omitempty"`
	Readonly bool    `protobuf:"varint,3,opt,name=readonly" json:"readonly,omitempty"`
	// User specified locator
	Locator *VolumeLocator `protobuf:"bytes,4,opt,name=locator" json:"locator,omitempty"`
	// Volume creation time
	Ctime *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=ctime" json:"ctime,omitempty"`
	// User specified VolumeSpec
	Spec *VolumeSpec `protobuf:"bytes,6,opt,name=spec" json:"spec,omitempty"`
	// Volume usage
	Usage uint64 `protobuf:"varint,7,opt,name=usage" json:"usage,omitempty"`
	// Time when an integrity check for run
	LastScan *google_protobuf.Timestamp `protobuf:"bytes,8,opt,name=last_scan,json=lastScan" json:"last_scan,omitempty"`
	// Format FSType type if any
	Format FSType       `protobuf:"varint,9,opt,name=format,enum=openstorage.api.FSType" json:"format,omitempty"`
	Status VolumeStatus `protobuf:"varint,10,opt,name=status,enum=openstorage.api.VolumeStatus" json:"status,omitempty"`
	State  VolumeState  `protobuf:"varint,11,opt,name=state,enum=openstorage.api.VolumeState" json:"state,omitempty"`
	// Machine ID (node) on which this volume is attached
	// Machine ID is a node instance identifier for clustered systems.
	AttachedOn string   `protobuf:"bytes,12,opt,name=attached_on,json=attachedOn" json:"attached_on,omitempty"`
	DevicePath string   `protobuf:"bytes,14,opt,name=device_path,json=devicePath" json:"device_path,omitempty"`
	AttachPath []string `protobuf:"bytes,15,rep,name=attach_path,json=attachPath" json:"attach_path,omitempty"`
	// List of ReplicaSets which provide storage for this volume, for clustered storage arrays
	ReplicaSets []*ReplicaSet `protobuf:"bytes,16,rep,name=replica_sets,json=replicaSets" json:"replica_sets,omitempty"`
	// Last recorded error
	Error string `protobuf:"bytes,17,opt,name=error" json:"error,omitempty"`
	// List of name value mapping of driver specific runtime information.
	RuntimeState     []*RuntimeStateMap `protobuf:"bytes,18,rep,name=runtime_state,json=runtimeState" json:"runtime_state,omitempty"`
	SecureDevicePath string             `protobuf:"bytes,19,opt,name=secure_device_path,json=secureDevicePath" json:"secure_device_path,omitempty"`
}

func (m *Volume) Reset()                    { *m = Volume{} }
func (m *Volume) String() string            { return proto.CompactTextString(m) }
func (*Volume) ProtoMessage()               {}
func (*Volume) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Volume) GetSource() *Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *Volume) GetLocator() *VolumeLocator {
	if m != nil {
		return m.Locator
	}
	return nil
}

func (m *Volume) GetCtime() *google_protobuf.Timestamp {
	if m != nil {
		return m.Ctime
	}
	return nil
}

func (m *Volume) GetSpec() *VolumeSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Volume) GetLastScan() *google_protobuf.Timestamp {
	if m != nil {
		return m.LastScan
	}
	return nil
}

func (m *Volume) GetReplicaSets() []*ReplicaSet {
	if m != nil {
		return m.ReplicaSets
	}
	return nil
}

func (m *Volume) GetRuntimeState() []*RuntimeStateMap {
	if m != nil {
		return m.RuntimeState
	}
	return nil
}

type Stats struct {
	// Reads completed successfully
	Reads uint64 `protobuf:"varint,1,opt,name=reads" json:"reads,omitempty"`
	// Time spent in reads in ms
	ReadMs    uint64 `protobuf:"varint,2,opt,name=read_ms,json=readMs" json:"read_ms,omitempty"`
	ReadBytes uint64 `protobuf:"varint,3,opt,name=read_bytes,json=readBytes" json:"read_bytes,omitempty"`
	// Writes completed successfully
	Writes uint64 `protobuf:"varint,4,opt,name=writes" json:"writes,omitempty"`
	// Time spent in writes in ms
	WriteMs    uint64 `protobuf:"varint,5,opt,name=write_ms,json=writeMs" json:"write_ms,omitempty"`
	WriteBytes uint64 `protobuf:"varint,6,opt,name=write_bytes,json=writeBytes" json:"write_bytes,omitempty"`
	// IOs curently in progress
	IoProgress uint64 `protobuf:"varint,7,opt,name=io_progress,json=ioProgress" json:"io_progress,omitempty"`
	// Time spent doing IOs ms
	IoMs uint64 `protobuf:"varint,8,opt,name=io_ms,json=ioMs" json:"io_ms,omitempty"`
	// BytesUsed
	BytesUsed uint64 `protobuf:"varint,9,opt,name=bytes_used,json=bytesUsed" json:"bytes_used,omitempty"`
	// Interval in ms during which stats were collected
	IntervalMs uint64 `protobuf:"varint,10,opt,name=interval_ms,json=intervalMs" json:"interval_ms,omitempty"`
}

func (m *Stats) Reset()                    { *m = Stats{} }
func (m *Stats) String() string            { return proto.CompactTextString(m) }
func (*Stats) ProtoMessage()               {}
func (*Stats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type Alert struct {
	// Id for Alert
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// Severity of the Alert
	Severity SeverityType `protobuf:"varint,2,opt,name=severity,enum=openstorage.api.SeverityType" json:"severity,omitempty"`
	// AlertType user defined alert type
	AlertType int64 `protobuf:"varint,3,opt,name=alert_type,json=alertType" json:"alert_type,omitempty"`
	// Message describing the Alert
	Message string `protobuf:"bytes,4,opt,name=message" json:"message,omitempty"`
	// Timestamp when Alert occured
	Timestamp *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=timestamp" json:"timestamp,omitempty"`
	// ResourceId where Alert occured
	ResourceId string `protobuf:"bytes,6,opt,name=resource_id,json=resourceId" json:"resource_id,omitempty"`
	// Resource where Alert occured
	Resource ResourceType `protobuf:"varint,7,opt,name=resource,enum=openstorage.api.ResourceType" json:"resource,omitempty"`
	// Cleared Flag
	Cleared bool `protobuf:"varint,8,opt,name=cleared" json:"cleared,omitempty"`
	// TTL in seconds for this Alert
	Ttl uint64 `protobuf:"varint,9,opt,name=ttl" json:"ttl,omitempty"`
}

func (m *Alert) Reset()                    { *m = Alert{} }
func (m *Alert) String() string            { return proto.CompactTextString(m) }
func (*Alert) ProtoMessage()               {}
func (*Alert) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Alert) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type Alerts struct {
	Alert []*Alert `protobuf:"bytes,1,rep,name=alert" json:"alert,omitempty"`
}

func (m *Alerts) Reset()                    { *m = Alerts{} }
func (m *Alerts) String() string            { return proto.CompactTextString(m) }
func (*Alerts) ProtoMessage()               {}
func (*Alerts) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Alerts) GetAlert() []*Alert {
	if m != nil {
		return m.Alert
	}
	return nil
}

type VolumeCreateRequest struct {
	// User specified volume name and labels
	Locator *VolumeLocator `protobuf:"bytes,1,opt,name=locator" json:"locator,omitempty"`
	// Source to create volume
	Source *Source `protobuf:"bytes,2,opt,name=source" json:"source,omitempty"`
	// The storage spec for the volume
	Spec *VolumeSpec `protobuf:"bytes,3,opt,name=spec" json:"spec,omitempty"`
}

func (m *VolumeCreateRequest) Reset()                    { *m = VolumeCreateRequest{} }
func (m *VolumeCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*VolumeCreateRequest) ProtoMessage()               {}
func (*VolumeCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *VolumeCreateRequest) GetLocator() *VolumeLocator {
	if m != nil {
		return m.Locator
	}
	return nil
}

func (m *VolumeCreateRequest) GetSource() *Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *VolumeCreateRequest) GetSpec() *VolumeSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

type VolumeResponse struct {
	Error string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *VolumeResponse) Reset()                    { *m = VolumeResponse{} }
func (m *VolumeResponse) String() string            { return proto.CompactTextString(m) }
func (*VolumeResponse) ProtoMessage()               {}
func (*VolumeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type VolumeCreateResponse struct {
	// ID of the newly created volume
	Id             string          `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	VolumeResponse *VolumeResponse `protobuf:"bytes,2,opt,name=volume_response,json=volumeResponse" json:"volume_response,omitempty"`
}

func (m *VolumeCreateResponse) Reset()                    { *m = VolumeCreateResponse{} }
func (m *VolumeCreateResponse) String() string            { return proto.CompactTextString(m) }
func (*VolumeCreateResponse) ProtoMessage()               {}
func (*VolumeCreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *VolumeCreateResponse) GetVolumeResponse() *VolumeResponse {
	if m != nil {
		return m.VolumeResponse
	}
	return nil
}

// VolumeStateAction specifies desired actions.
type VolumeStateAction struct {
	// Attach or Detach volume
	Attach VolumeActionParam `protobuf:"varint,1,opt,name=attach,enum=openstorage.api.VolumeActionParam" json:"attach,omitempty"`
	// Mount or unmount volume
	Mount     VolumeActionParam `protobuf:"varint,2,opt,name=mount,enum=openstorage.api.VolumeActionParam" json:"mount,omitempty"`
	MountPath string            `protobuf:"bytes,3,opt,name=mount_path,json=mountPath" json:"mount_path,omitempty"`
	// Device path returned in attach
	DevicePath string `protobuf:"bytes,4,opt,name=device_path,json=devicePath" json:"device_path,omitempty"`
}

func (m *VolumeStateAction) Reset()                    { *m = VolumeStateAction{} }
func (m *VolumeStateAction) String() string            { return proto.CompactTextString(m) }
func (*VolumeStateAction) ProtoMessage()               {}
func (*VolumeStateAction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type VolumeSetRequest struct {
	// User specified volume name and labels
	Locator *VolumeLocator `protobuf:"bytes,1,opt,name=locator" json:"locator,omitempty"`
	// The storage spec for the volume
	Spec *VolumeSpec `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
	// State modification on this volume.
	Action *VolumeStateAction `protobuf:"bytes,3,opt,name=action" json:"action,omitempty"`
}

func (m *VolumeSetRequest) Reset()                    { *m = VolumeSetRequest{} }
func (m *VolumeSetRequest) String() string            { return proto.CompactTextString(m) }
func (*VolumeSetRequest) ProtoMessage()               {}
func (*VolumeSetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *VolumeSetRequest) GetLocator() *VolumeLocator {
	if m != nil {
		return m.Locator
	}
	return nil
}

func (m *VolumeSetRequest) GetSpec() *VolumeSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *VolumeSetRequest) GetAction() *VolumeStateAction {
	if m != nil {
		return m.Action
	}
	return nil
}

type VolumeSetResponse struct {
	Volume         *Volume         `protobuf:"bytes,1,opt,name=volume" json:"volume,omitempty"`
	VolumeResponse *VolumeResponse `protobuf:"bytes,2,opt,name=volume_response,json=volumeResponse" json:"volume_response,omitempty"`
}

func (m *VolumeSetResponse) Reset()                    { *m = VolumeSetResponse{} }
func (m *VolumeSetResponse) String() string            { return proto.CompactTextString(m) }
func (*VolumeSetResponse) ProtoMessage()               {}
func (*VolumeSetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *VolumeSetResponse) GetVolume() *Volume {
	if m != nil {
		return m.Volume
	}
	return nil
}

func (m *VolumeSetResponse) GetVolumeResponse() *VolumeResponse {
	if m != nil {
		return m.VolumeResponse
	}
	return nil
}

type SnapCreateRequest struct {
	// volume id
	Id       string         `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Locator  *VolumeLocator `protobuf:"bytes,2,opt,name=locator" json:"locator,omitempty"`
	Readonly bool           `protobuf:"varint,3,opt,name=readonly" json:"readonly,omitempty"`
}

func (m *SnapCreateRequest) Reset()                    { *m = SnapCreateRequest{} }
func (m *SnapCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*SnapCreateRequest) ProtoMessage()               {}
func (*SnapCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *SnapCreateRequest) GetLocator() *VolumeLocator {
	if m != nil {
		return m.Locator
	}
	return nil
}

type SnapCreateResponse struct {
	VolumeCreateResponse *VolumeCreateResponse `protobuf:"bytes,1,opt,name=volume_create_response,json=volumeCreateResponse" json:"volume_create_response,omitempty"`
}

func (m *SnapCreateResponse) Reset()                    { *m = SnapCreateResponse{} }
func (m *SnapCreateResponse) String() string            { return proto.CompactTextString(m) }
func (*SnapCreateResponse) ProtoMessage()               {}
func (*SnapCreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *SnapCreateResponse) GetVolumeCreateResponse() *VolumeCreateResponse {
	if m != nil {
		return m.VolumeCreateResponse
	}
	return nil
}

type VolumeInfo struct {
	VolumeId string      `protobuf:"bytes,1,opt,name=volume_id,json=volumeId" json:"volume_id,omitempty"`
	Path     string      `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Storage  *VolumeSpec `protobuf:"bytes,3,opt,name=storage" json:"storage,omitempty"`
}

func (m *VolumeInfo) Reset()                    { *m = VolumeInfo{} }
func (m *VolumeInfo) String() string            { return proto.CompactTextString(m) }
func (*VolumeInfo) ProtoMessage()               {}
func (*VolumeInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *VolumeInfo) GetStorage() *VolumeSpec {
	if m != nil {
		return m.Storage
	}
	return nil
}

// GraphDriverChanges represent a list of changes between the filesystem layers
// specified by the ID and Parent.  // Parent may be an empty string, in which
// case there is no parent.
// Where the Path is the filesystem path within the layered filesystem
type GraphDriverChanges struct {
	Path string                `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Kind GraphDriverChangeType `protobuf:"varint,2,opt,name=kind,enum=openstorage.api.GraphDriverChangeType" json:"kind,omitempty"`
}

func (m *GraphDriverChanges) Reset()                    { *m = GraphDriverChanges{} }
func (m *GraphDriverChanges) String() string            { return proto.CompactTextString(m) }
func (*GraphDriverChanges) ProtoMessage()               {}
func (*GraphDriverChanges) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

type ClusterResponse struct {
	Error string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *ClusterResponse) Reset()                    { *m = ClusterResponse{} }
func (m *ClusterResponse) String() string            { return proto.CompactTextString(m) }
func (*ClusterResponse) ProtoMessage()               {}
func (*ClusterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

type ActiveRequest struct {
	ReqestKV map[int64]string `protobuf:"bytes,1,rep,name=ReqestKV,json=reqestKV" json:"ReqestKV,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ActiveRequest) Reset()                    { *m = ActiveRequest{} }
func (m *ActiveRequest) String() string            { return proto.CompactTextString(m) }
func (*ActiveRequest) ProtoMessage()               {}
func (*ActiveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *ActiveRequest) GetReqestKV() map[int64]string {
	if m != nil {
		return m.ReqestKV
	}
	return nil
}

type ActiveRequests struct {
	RequestCount  int64            `protobuf:"varint,1,opt,name=RequestCount,json=requestCount" json:"RequestCount,omitempty"`
	ActiveRequest []*ActiveRequest `protobuf:"bytes,2,rep,name=ActiveRequest,json=activeRequest" json:"ActiveRequest,omitempty"`
}

func (m *ActiveRequests) Reset()                    { *m = ActiveRequests{} }
func (m *ActiveRequests) String() string            { return proto.CompactTextString(m) }
func (*ActiveRequests) ProtoMessage()               {}
func (*ActiveRequests) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *ActiveRequests) GetActiveRequest() []*ActiveRequest {
	if m != nil {
		return m.ActiveRequest
	}
	return nil
}

func init() {
	proto.RegisterType((*StorageResource)(nil), "openstorage.api.StorageResource")
	proto.RegisterType((*VolumeLocator)(nil), "openstorage.api.VolumeLocator")
	proto.RegisterType((*Source)(nil), "openstorage.api.Source")
	proto.RegisterType((*VolumeSpec)(nil), "openstorage.api.VolumeSpec")
	proto.RegisterType((*ReplicaSet)(nil), "openstorage.api.ReplicaSet")
	proto.RegisterType((*RuntimeStateMap)(nil), "openstorage.api.RuntimeStateMap")
	proto.RegisterType((*Volume)(nil), "openstorage.api.Volume")
	proto.RegisterType((*Stats)(nil), "openstorage.api.Stats")
	proto.RegisterType((*Alert)(nil), "openstorage.api.Alert")
	proto.RegisterType((*Alerts)(nil), "openstorage.api.Alerts")
	proto.RegisterType((*VolumeCreateRequest)(nil), "openstorage.api.VolumeCreateRequest")
	proto.RegisterType((*VolumeResponse)(nil), "openstorage.api.VolumeResponse")
	proto.RegisterType((*VolumeCreateResponse)(nil), "openstorage.api.VolumeCreateResponse")
	proto.RegisterType((*VolumeStateAction)(nil), "openstorage.api.VolumeStateAction")
	proto.RegisterType((*VolumeSetRequest)(nil), "openstorage.api.VolumeSetRequest")
	proto.RegisterType((*VolumeSetResponse)(nil), "openstorage.api.VolumeSetResponse")
	proto.RegisterType((*SnapCreateRequest)(nil), "openstorage.api.SnapCreateRequest")
	proto.RegisterType((*SnapCreateResponse)(nil), "openstorage.api.SnapCreateResponse")
	proto.RegisterType((*VolumeInfo)(nil), "openstorage.api.VolumeInfo")
	proto.RegisterType((*GraphDriverChanges)(nil), "openstorage.api.GraphDriverChanges")
	proto.RegisterType((*ClusterResponse)(nil), "openstorage.api.ClusterResponse")
	proto.RegisterType((*ActiveRequest)(nil), "openstorage.api.ActiveRequest")
	proto.RegisterType((*ActiveRequests)(nil), "openstorage.api.ActiveRequests")
	proto.RegisterEnum("openstorage.api.Status", Status_name, Status_value)
	proto.RegisterEnum("openstorage.api.DriverType", DriverType_name, DriverType_value)
	proto.RegisterEnum("openstorage.api.FSType", FSType_name, FSType_value)
	proto.RegisterEnum("openstorage.api.GraphDriverChangeType", GraphDriverChangeType_name, GraphDriverChangeType_value)
	proto.RegisterEnum("openstorage.api.SeverityType", SeverityType_name, SeverityType_value)
	proto.RegisterEnum("openstorage.api.ResourceType", ResourceType_name, ResourceType_value)
	proto.RegisterEnum("openstorage.api.AlertActionType", AlertActionType_name, AlertActionType_value)
	proto.RegisterEnum("openstorage.api.VolumeActionParam", VolumeActionParam_name, VolumeActionParam_value)
	proto.RegisterEnum("openstorage.api.CosType", CosType_name, CosType_value)
	proto.RegisterEnum("openstorage.api.VolumeState", VolumeState_name, VolumeState_value)
	proto.RegisterEnum("openstorage.api.VolumeStatus", VolumeStatus_name, VolumeStatus_value)
	proto.RegisterEnum("openstorage.api.StorageMedium", StorageMedium_name, StorageMedium_value)
	proto.RegisterEnum("openstorage.api.ClusterNotify", ClusterNotify_name, ClusterNotify_value)
}

func init() { proto.RegisterFile("api/api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2421 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x58, 0xcd, 0x72, 0xe3, 0xc6,
	0xf1, 0x37, 0xf8, 0xcd, 0xa6, 0x28, 0x41, 0x23, 0x59, 0xcb, 0x95, 0xf7, 0x43, 0x66, 0xfd, 0xed,
	0xbf, 0x8a, 0xd9, 0x48, 0x2e, 0xc5, 0x76, 0x36, 0x9b, 0x54, 0x52, 0x10, 0x09, 0x4a, 0x88, 0xf9,
	0xa1, 0x0c, 0x40, 0xc9, 0xeb, 0x54, 0x0a, 0x85, 0x25, 0x67, 0x25, 0x64, 0x49, 0x00, 0xc2, 0x80,
	0x4a, 0xc9, 0x2f, 0x90, 0x4b, 0x2a, 0x39, 0x25, 0x55, 0xa9, 0x1c, 0x72, 0x8f, 0x4f, 0x39, 0xa6,
	0xf2, 0x04, 0x39, 0xe4, 0x9a, 0x6b, 0x9e, 0x21, 0x6f, 0x90, 0x9a, 0x0f, 0x50, 0x00, 0x49, 0x69,
	0xb5, 0x15, 0xdf, 0xa6, 0x7f, 0xdd, 0xd3, 0xd3, 0xdd, 0xd3, 0xdd, 0xd3, 0x00, 0x54, 0x9d, 0xc0,
	0xdd, 0x77, 0x02, 0x77, 0x2f, 0x08, 0xfd, 0xc8, 0x47, 0x6b, 0x7e, 0x40, 0x3c, 0x1a, 0xf9, 0xa1,
	0x73, 0x4e, 0xf6, 0x9c, 0xc0, 0xdd, 0x7e, 0x7a, 0xee, 0xfb, 0xe7, 0x63, 0xb2, 0xcf, 0xd9, 0xaf,
	0xa6, 0xaf, 0xf7, 0x23, 0x77, 0x42, 0x68, 0xe4, 0x4c, 0x02, 0xb1, 0xa3, 0xfe, 0x9f, 0x0c, 0xac,
	0x99, 0x62, 0x03, 0x26, 0xd4, 0x9f, 0x86, 0x43, 0x82, 0x56, 0x21, 0xe3, 0x8e, 0x6a, 0xca, 0x8e,
	0xb2, 0x5b, 0xc6, 0x19, 0x77, 0x84, 0x10, 0xe4, 0x02, 0x27, 0xba, 0xa8, 0x65, 0x38, 0xc2, 0xd7,
	0xe8, 0x73, 0x28, 0x4c, 0xc8, 0xc8, 0x9d, 0x4e, 0x6a, 0xd9, 0x1d, 0x65, 0x77, 0xf5, 0xe0, 0xc9,
	0xde, 0xdc, 0xd1, 0x7b, 0x52, 0x6b, 0x97, 0x4b, 0x61, 0x29, 0x8d, 0xb6, 0xa0, 0xe0, 0x7b, 0x63,
	0xd7, 0x23, 0xb5, 0xdc, 0x8e, 0xb2, 0x5b, 0xc2, 0x92, 0x62, 0x67, 0xb8, 0x7e, 0x40, 0x6b, 0xf9,
	0x1d, 0x65, 0x37, 0x87, 0xf9, 0x1a, 0x7d, 0x00, 0x65, 0x4a, 0x2e, 0xed, 0x5f, 0x85, 0x6e, 0x44,
	0x6a, 0x85, 0x1d, 0x65, 0x57, 0xc1, 0x25, 0x4a, 0x2e, 0xcf, 0x18, 0x8d, 0x1e, 0x02, 0x5b, 0xdb,
	0x21, 0x71, 0x46, 0xb5, 0x22, 0xe7, 0x15, 0x29, 0xb9, 0xc4, 0xc4, 0x19, 0xb1, 0x33, 0x42, 0xc7,
	0x1b, 0xe1, 0xb3, 0x5a, 0x89, 0x33, 0x24, 0xc5, 0xce, 0xa0, 0xee, 0xd7, 0xa4, 0x56, 0x16, 0x67,
	0xb0, 0x35, 0xc3, 0xa6, 0x94, 0x8c, 0x6a, 0x20, 0x30, 0xb6, 0x46, 0x1f, 0xc1, 0x6a, 0xe8, 0x47,
	0x4e, 0xe4, 0xfa, 0x9e, 0x4d, 0x03, 0x42, 0x46, 0xb5, 0x0a, 0xf7, 0xbc, 0x1a, 0xa3, 0x26, 0x03,
	0xd1, 0xf7, 0xa1, 0x3c, 0x76, 0x68, 0x64, 0xd3, 0xa1, 0xe3, 0xd5, 0x56, 0x76, 0x94, 0xdd, 0xca,
	0xc1, 0xf6, 0x9e, 0x88, 0xf7, 0x5e, 0x1c, 0xef, 0x3d, 0x2b, 0x8e, 0x37, 0x2e, 0x31, 0x61, 0x73,
	0xe8, 0x78, 0xf5, 0xbf, 0x2b, 0x50, 0x3d, 0xf5, 0xc7, 0xd3, 0x09, 0xe9, 0xf8, 0x43, 0x27, 0xf2,
	0x43, 0x66, 0x85, 0xe7, 0x4c, 0x88, 0x8c, 0x39, 0x5f, 0xa3, 0x01, 0x54, 0xaf, 0xb8, 0x90, 0x3d,
	0x76, 0x5e, 0x91, 0x31, 0xad, 0x65, 0x76, 0xb2, 0xbb, 0x95, 0x83, 0x4f, 0x16, 0x02, 0x9d, 0x52,
	0x15, 0x53, 0x7c, 0x8b, 0xee, 0x45, 0xe1, 0x35, 0x5e, 0xb9, 0x4a, 0x40, 0xdb, 0x3f, 0x81, 0xf5,
	0x05, 0x11, 0xa4, 0x42, 0xf6, 0x0d, 0xb9, 0x96, 0xc7, 0xb3, 0x25, 0xda, 0x84, 0xfc, 0x95, 0x33,
	0x9e, 0x12, 0x79, 0xe9, 0x82, 0x78, 0x91, 0x79, 0xae, 0xd4, 0x3f, 0x85, 0x82, 0x29, 0xf2, 0x64,
	0x0b, 0x0a, 0x81, 0x13, 0x12, 0x2f, 0x92, 0x1b, 0x25, 0xc5, 0xe3, 0xcc, 0xa2, 0x26, 0xf3, 0x85,
	0xad, 0xeb, 0xff, 0xca, 0x01, 0x88, 0x73, 0xcd, 0x80, 0x0c, 0xd1, 0x23, 0x28, 0x93, 0xe0, 0x82,
	0x4c, 0x48, 0xe8, 0x8c, 0xf9, 0xee, 0x12, 0xbe, 0x01, 0x66, 0x17, 0x95, 0x49, 0x5c, 0xd4, 0x3e,
	0x14, 0x5e, 0xfb, 0xe1, 0xc4, 0x89, 0x64, 0xc2, 0x3d, 0x58, 0x88, 0x43, 0xdb, 0xb4, 0xae, 0x03,
	0x82, 0xa5, 0x18, 0x7a, 0x0c, 0xf0, 0x6a, 0xec, 0x0f, 0xdf, 0xd8, 0x5c, 0x15, 0xcb, 0xb6, 0x2c,
	0x2e, 0x73, 0xc4, 0x64, 0xfa, 0x1e, 0x42, 0xe9, 0xc2, 0xb1, 0xc7, 0xe4, 0x8a, 0x8c, 0x79, 0xd2,
	0x65, 0x71, 0xf1, 0xc2, 0xe9, 0x30, 0x92, 0x45, 0x63, 0xe8, 0x53, 0x9e, 0x71, 0x55, 0xcc, 0x96,
	0xcc, 0xd3, 0x11, 0x19, 0x4d, 0x03, 0xc2, 0x53, 0xad, 0x84, 0x25, 0x85, 0xbe, 0x03, 0xeb, 0xd4,
	0x73, 0x02, 0x7a, 0xe1, 0x47, 0xb6, 0xeb, 0x45, 0x24, 0xbc, 0x72, 0xc6, 0x3c, 0xe9, 0xaa, 0x58,
	0x8d, 0x19, 0x86, 0xc4, 0x11, 0x9e, 0xbf, 0xd0, 0x32, 0xbf, 0xd0, 0xef, 0xde, 0x72, 0xa1, 0x2c,
	0x4e, 0x6f, 0xbb, 0x4d, 0x66, 0x18, 0xbd, 0x70, 0x42, 0x99, 0xc0, 0x25, 0x2c, 0x29, 0xf4, 0x23,
	0xa8, 0x84, 0x24, 0x18, 0xbb, 0x43, 0xc7, 0xa6, 0x24, 0xe2, 0xf9, 0x5b, 0x39, 0xf8, 0x60, 0xe1,
	0x24, 0x2c, 0x64, 0x4c, 0x12, 0x61, 0x08, 0x67, 0x6b, 0xe6, 0x96, 0x73, 0x7e, 0x1e, 0x92, 0x73,
	0x51, 0x03, 0x22, 0x48, 0x2b, 0xc2, 0xad, 0x04, 0x43, 0x44, 0x8b, 0x5d, 0xa5, 0x37, 0x0c, 0xaf,
	0x83, 0x88, 0x8c, 0x6a, 0x55, 0x79, 0x95, 0x31, 0x80, 0x9e, 0x00, 0x04, 0x0e, 0xa5, 0xc1, 0x45,
	0xe8, 0x50, 0x52, 0x5b, 0xe5, 0x19, 0x91, 0x40, 0xfe, 0xf7, 0x74, 0xac, 0x03, 0xdc, 0x78, 0xc1,
	0xe4, 0x3c, 0x7f, 0x44, 0x68, 0x4d, 0xd9, 0xc9, 0x32, 0x39, 0x4e, 0xd4, 0xbf, 0x51, 0x60, 0x0d,
	0x4f, 0x3d, 0xd6, 0xfb, 0xcc, 0xc8, 0x89, 0x48, 0xd7, 0x09, 0xd0, 0x19, 0x54, 0x43, 0x01, 0xd9,
	0x94, 0x61, 0x7c, 0x47, 0xe5, 0xe0, 0x60, 0x31, 0x46, 0xe9, 0x8d, 0x29, 0x5a, 0x5e, 0x49, 0x98,
	0x80, 0x98, 0x47, 0x0b, 0x22, 0xef, 0xe4, 0xd1, 0x9f, 0x0a, 0x50, 0x10, 0x31, 0x59, 0xe8, 0xc4,
	0xfb, 0x50, 0x10, 0x3d, 0x9a, 0xef, 0xaa, 0x2c, 0x29, 0x02, 0x51, 0x9a, 0x58, 0x8a, 0xa1, 0x6d,
	0x28, 0xb1, 0x0e, 0xe9, 0x7b, 0xe3, 0x6b, 0x5e, 0x37, 0x25, 0x3c, 0xa3, 0xd1, 0x73, 0x28, 0x8e,
	0x45, 0xd3, 0xe0, 0xd5, 0x51, 0x59, 0xd2, 0xc3, 0x53, 0xad, 0x05, 0xc7, 0xe2, 0xe8, 0x13, 0xc8,
	0x0f, 0x99, 0x83, 0xbc, 0x70, 0xee, 0xee, 0x7a, 0x42, 0x10, 0xed, 0x43, 0x8e, 0x06, 0x64, 0xc8,
	0x6b, 0x6a, 0x59, 0x22, 0xde, 0xa4, 0x3c, 0xe6, 0x82, 0x2c, 0x3c, 0x53, 0xea, 0x9c, 0x8b, 0x82,
	0xcb, 0x61, 0x41, 0xa4, 0x5b, 0x6e, 0xe9, 0xfe, 0x2d, 0x37, 0xd1, 0x3d, 0xca, 0xf7, 0xeb, 0x1e,
	0x9f, 0x41, 0x81, 0xa5, 0xc5, 0x94, 0xf2, 0xc2, 0x5a, 0x3d, 0x78, 0x7c, 0x9b, 0xc9, 0x5c, 0x08,
	0x4b, 0x61, 0x74, 0x00, 0x79, 0x91, 0x4d, 0x15, 0xbe, 0xeb, 0xd1, 0x1d, 0xbb, 0x08, 0x16, 0xa2,
	0xe8, 0x29, 0x54, 0x9c, 0x28, 0x72, 0x86, 0x17, 0x64, 0x64, 0xfb, 0xe2, 0x25, 0x29, 0x63, 0x88,
	0xa1, 0xbe, 0xc7, 0x04, 0x46, 0xe4, 0xca, 0x1d, 0x12, 0x9b, 0x3f, 0xc3, 0xb2, 0x88, 0x04, 0x74,
	0xc2, 0x1e, 0xe3, 0x99, 0x06, 0x21, 0xb0, 0xc6, 0x73, 0x5f, 0x6a, 0xe0, 0x02, 0x3f, 0x86, 0x95,
	0x44, 0x3b, 0xa0, 0x35, 0x95, 0xe7, 0xfa, 0x9d, 0xfd, 0xa0, 0x72, 0xd3, 0x0f, 0x28, 0xbb, 0x0d,
	0x12, 0x86, 0x7e, 0x58, 0x5b, 0x17, 0xc9, 0xca, 0x09, 0xa4, 0xcf, 0x97, 0x10, 0xe2, 0x6a, 0x77,
	0xde, 0x56, 0x42, 0xe9, 0x82, 0x41, 0xcf, 0x00, 0x51, 0x32, 0x9c, 0x86, 0xc4, 0x4e, 0x7a, 0xb9,
	0xc1, 0x4f, 0x52, 0x05, 0xa7, 0x35, 0xf3, 0xb5, 0xfe, 0xe7, 0x0c, 0xe4, 0xd9, 0x3e, 0x6e, 0x14,
	0xcb, 0x65, 0xca, 0xeb, 0x23, 0x87, 0x05, 0x81, 0x1e, 0x40, 0x91, 0x2d, 0xec, 0x09, 0x95, 0xcf,
	0x47, 0x81, 0x91, 0x5d, 0xca, 0xde, 0x03, 0xce, 0x78, 0x75, 0x1d, 0x11, 0xca, 0x8b, 0x21, 0x87,
	0xcb, 0x0c, 0x39, 0x64, 0x00, 0xeb, 0xa4, 0x7c, 0xd0, 0xa0, 0xbc, 0x18, 0x72, 0x58, 0x52, 0xec,
	0x9d, 0xe0, 0x2b, 0xa6, 0x50, 0x0c, 0x27, 0x45, 0x4e, 0x77, 0x29, 0x0b, 0xbb, 0x60, 0x09, 0x95,
	0x05, 0xce, 0x05, 0x0e, 0x09, 0x9d, 0x4f, 0xa1, 0xe2, 0xfa, 0x76, 0x10, 0xfa, 0xe7, 0x21, 0xa1,
	0x54, 0xa6, 0x32, 0xb8, 0xfe, 0x89, 0x44, 0xd0, 0x06, 0xe4, 0x5d, 0x9f, 0x69, 0x2e, 0xc5, 0x63,
	0x8f, 0x30, 0x94, 0x2b, 0xb4, 0xf9, 0x60, 0x22, 0x86, 0x95, 0x32, 0x47, 0x06, 0x6c, 0x3a, 0x61,
	0x4a, 0xe5, 0x93, 0xc2, 0x76, 0x82, 0x54, 0x2a, 0xa1, 0x2e, 0xad, 0xff, 0x33, 0x03, 0x79, 0x6d,
	0x4c, 0xc2, 0x28, 0xd1, 0x3e, 0xb2, 0xbc, 0x7d, 0xfc, 0x80, 0xcd, 0x4c, 0x57, 0x24, 0x74, 0xa3,
	0x6b, 0x1e, 0x9c, 0x65, 0x69, 0x6d, 0x4a, 0x01, 0x5e, 0x0d, 0x33, 0x71, 0x66, 0x94, 0xc3, 0x74,
	0xda, 0xd1, 0x75, 0x40, 0x78, 0xf4, 0xb2, 0xb8, 0xcc, 0x11, 0x26, 0x88, 0x6a, 0x50, 0x9c, 0x10,
	0xca, 0x0b, 0x36, 0xc7, 0x2f, 0x2e, 0x26, 0xd1, 0x73, 0x28, 0xcf, 0x66, 0xce, 0x7b, 0xf4, 0x8b,
	0x1b, 0x61, 0xe6, 0x68, 0x28, 0x47, 0x52, 0xdb, 0x1d, 0xf1, 0xf0, 0x96, 0xd9, 0x33, 0x25, 0x20,
	0x83, 0xbb, 0x13, 0x53, 0x3c, 0xb6, 0xcb, 0xdc, 0x89, 0x87, 0x5a, 0xe1, 0x4e, 0x2c, 0xce, 0xec,
	0x1d, 0x8e, 0x09, 0x7f, 0x38, 0x4b, 0xbc, 0x2d, 0xc6, 0x24, 0xeb, 0xd4, 0x51, 0x34, 0x96, 0x61,
	0x67, 0xcb, 0xfa, 0xe7, 0x50, 0xe0, 0xe1, 0xa4, 0xe8, 0x19, 0xe4, 0xb9, 0xcb, 0xf2, 0xad, 0xd8,
	0x5a, 0x38, 0x8d, 0xcb, 0x61, 0x21, 0x54, 0xff, 0xab, 0x02, 0x1b, 0xa2, 0xdc, 0x9b, 0x21, 0x61,
	0xf5, 0x4e, 0x2e, 0xa7, 0x84, 0x46, 0xc9, 0xbe, 0xab, 0xbc, 0x5b, 0xdf, 0x7d, 0xe7, 0xf6, 0x1f,
	0xb7, 0xdd, 0xec, 0x3d, 0xdb, 0x6e, 0xfd, 0x63, 0x58, 0x15, 0x18, 0x26, 0x34, 0xf0, 0x3d, 0x4a,
	0x6e, 0x4a, 0x5f, 0x49, 0x94, 0x7e, 0x3d, 0x80, 0xcd, 0xb4, 0x6b, 0x52, 0x7a, 0xfe, 0xc1, 0x3a,
	0x86, 0x35, 0x39, 0xf3, 0x84, 0x52, 0x44, 0x9a, 0xfe, 0xf4, 0x16, 0x5b, 0x62, 0x4d, 0x78, 0xf5,
	0x2a, 0x45, 0xd7, 0xff, 0xa1, 0xc4, 0x93, 0x02, 0xef, 0x1a, 0xda, 0x90, 0x4d, 0x20, 0xe8, 0x05,
	0x14, 0x44, 0x9b, 0xe3, 0x67, 0xae, 0x1e, 0xd4, 0x6f, 0x51, 0x2b, 0xc4, 0x4f, 0x9c, 0xd0, 0x99,
	0x60, 0xb9, 0x03, 0x3d, 0x87, 0xfc, 0xc4, 0x9f, 0x7a, 0x91, 0x2c, 0x85, 0xfb, 0x6c, 0x15, 0x1b,
	0x58, 0x31, 0xf0, 0x85, 0xe8, 0x54, 0x59, 0xee, 0x6d, 0x99, 0x23, 0x71, 0x3b, 0x4e, 0x76, 0xb2,
	0xdc, 0x7c, 0xbf, 0xae, 0xff, 0x4d, 0x01, 0x55, 0xfa, 0x42, 0xa2, 0x6f, 0x23, 0x2d, 0xc4, 0x2d,
	0x67, 0xee, 0xfb, 0xb8, 0xb2, 0xa8, 0x71, 0xaf, 0x64, 0x62, 0xd4, 0xef, 0x7a, 0xa6, 0x84, 0xff,
	0x58, 0xee, 0xa8, 0xff, 0xf6, 0xe6, 0x1e, 0x98, 0xed, 0xf2, 0xde, 0xf7, 0xa1, 0x20, 0xee, 0x4b,
	0xda, 0xfe, 0xe0, 0xb6, 0xeb, 0x95, 0x62, 0xdf, 0x62, 0x62, 0x5c, 0xc3, 0xba, 0xe9, 0x39, 0x41,
	0xba, 0xc6, 0xe6, 0xf3, 0x30, 0x11, 0xdc, 0xcc, 0xbb, 0x05, 0xf7, 0x8e, 0x09, 0xaa, 0x7e, 0x09,
	0x28, 0x79, 0xb4, 0x8c, 0xc5, 0xcf, 0x61, 0x4b, 0xba, 0x36, 0xe4, 0x8c, 0x1b, 0x0f, 0x45, 0x6c,
	0x3e, 0xba, 0xe5, 0xe8, 0xb4, 0x1a, 0xbc, 0x79, 0xb5, 0x04, 0xad, 0x47, 0xf1, 0x67, 0x94, 0xe1,
	0xbd, 0xf6, 0xd9, 0x17, 0xb2, 0x3c, 0x6a, 0xe6, 0x6d, 0x49, 0x00, 0xc6, 0xf2, 0xcf, 0xf6, 0xcf,
	0xa0, 0x28, 0x0f, 0xbe, 0x4f, 0x4f, 0x88, 0x65, 0xeb, 0x23, 0x40, 0x47, 0xa1, 0x13, 0x5c, 0xb4,
	0x42, 0xf7, 0x8a, 0x84, 0xcd, 0x0b, 0xc7, 0x3b, 0x27, 0x74, 0x76, 0x80, 0x92, 0x38, 0xe0, 0x05,
	0xe4, 0xde, 0xb8, 0xde, 0x48, 0xd6, 0xd4, 0xc7, 0x0b, 0xda, 0x17, 0xd4, 0xf0, 0xc6, 0xcc, 0xf7,
	0xd4, 0xff, 0x1f, 0xd6, 0x9a, 0xe3, 0x29, 0x8d, 0x48, 0xf8, 0x96, 0xee, 0xf3, 0x07, 0x05, 0xaa,
	0x2c, 0x2d, 0xaf, 0x66, 0xf7, 0x7d, 0x0c, 0x25, 0x4c, 0x2e, 0x09, 0x8d, 0xbe, 0x38, 0x95, 0xcd,
	0xf9, 0xd9, 0x62, 0x73, 0x4e, 0xee, 0xd8, 0x8b, 0xc5, 0xc5, 0x08, 0x5f, 0x0a, 0x25, 0xb9, 0xfd,
	0x43, 0xa8, 0xa6, 0x58, 0xc9, 0xd1, 0x3d, 0xfb, 0xb6, 0xd1, 0xfd, 0x6b, 0x58, 0x4d, 0x9d, 0x42,
	0x51, 0x1d, 0x56, 0xe4, 0xba, 0xc9, 0x7b, 0x8d, 0x50, 0xb3, 0x12, 0x26, 0x30, 0xd4, 0x9a, 0xf3,
	0x46, 0x7e, 0xe9, 0x3f, 0xb9, 0xdb, 0x03, 0x5c, 0x75, 0x92, 0x64, 0xe3, 0x2f, 0x0a, 0x14, 0xc4,
	0x34, 0x8a, 0xd6, 0xa0, 0x62, 0x5a, 0x9a, 0x35, 0x30, 0xed, 0x5e, 0xbf, 0xa7, 0xab, 0xef, 0x25,
	0x00, 0xa3, 0x67, 0x58, 0xaa, 0x82, 0xaa, 0x50, 0x96, 0x40, 0xff, 0x0b, 0x35, 0x83, 0x10, 0xac,
	0xc6, 0x64, 0xbb, 0xdd, 0x31, 0x7a, 0xba, 0x9a, 0x45, 0x2a, 0xac, 0x48, 0x4c, 0xc7, 0xb8, 0x8f,
	0xd5, 0x1c, 0xaa, 0xc1, 0xe6, 0x4c, 0xad, 0x65, 0x1b, 0x3d, 0xfb, 0x67, 0x83, 0x3e, 0x1e, 0x74,
	0xd5, 0x3c, 0x7a, 0x00, 0x1b, 0x92, 0xd3, 0xd2, 0x9b, 0xfd, 0x6e, 0xd7, 0x30, 0x4d, 0xa3, 0xdf,
	0x53, 0x0b, 0x68, 0x0b, 0x90, 0x64, 0x74, 0x35, 0xa3, 0x67, 0xe9, 0x3d, 0xad, 0xd7, 0xd4, 0xd5,
	0x62, 0xe3, 0x8f, 0x0a, 0x80, 0xc8, 0x02, 0x3e, 0x3e, 0x6c, 0x82, 0xda, 0xc2, 0xc6, 0xa9, 0x8e,
	0x6d, 0xeb, 0xe5, 0x89, 0x1e, 0x5b, 0x3d, 0x87, 0xb6, 0x8d, 0x8e, 0xae, 0x2a, 0xe8, 0x7d, 0x58,
	0x4f, 0xa2, 0x87, 0x9d, 0x7e, 0x93, 0xb9, 0xb0, 0x05, 0x28, 0x09, 0xf7, 0x0f, 0x7f, 0xaa, 0x37,
	0x2d, 0x35, 0x8b, 0x1e, 0xc2, 0xfb, 0x49, 0xbc, 0xd9, 0x19, 0x98, 0x96, 0x8e, 0xf5, 0x96, 0x9a,
	0x9b, 0xd7, 0x74, 0x84, 0xb5, 0x93, 0x63, 0x35, 0xdf, 0xf8, 0xbd, 0x02, 0x05, 0xf1, 0x35, 0xc0,
	0x62, 0xd0, 0x36, 0x53, 0x36, 0xad, 0x43, 0x35, 0x46, 0x0e, 0x2d, 0xdc, 0x36, 0x55, 0x25, 0x29,
	0xa4, 0x7f, 0x69, 0x7d, 0xaa, 0x66, 0x92, 0x48, 0x7b, 0x60, 0xb2, 0x60, 0xae, 0x41, 0x65, 0xa6,
	0xa8, 0x6d, 0xaa, 0xb9, 0x24, 0x70, 0xda, 0x36, 0xd5, 0x7c, 0x12, 0xf8, 0xb2, 0x6d, 0xaa, 0x85,
	0x24, 0xf0, 0x55, 0xdb, 0x54, 0x8b, 0x8d, 0x6f, 0x14, 0x78, 0x7f, 0x69, 0xf9, 0xa0, 0x0f, 0xe1,
	0x31, 0x37, 0xde, 0x96, 0xee, 0x34, 0x8f, 0xb5, 0xde, 0x91, 0x9e, 0xb2, 0xfb, 0x23, 0xf8, 0xf0,
	0x56, 0x91, 0x6e, 0xbf, 0x65, 0xb4, 0x0d, 0xbd, 0xa5, 0x2a, 0xa8, 0x0e, 0x4f, 0x6e, 0x15, 0xd3,
	0x5a, 0x2d, 0xbd, 0xa5, 0x66, 0xd0, 0xff, 0xc1, 0xce, 0xad, 0x32, 0x2d, 0xbd, 0xa3, 0x5b, 0x7a,
	0x4b, 0xcd, 0x36, 0x22, 0x58, 0x49, 0x8e, 0x92, 0x3c, 0x13, 0xf4, 0x53, 0x1d, 0x1b, 0xd6, 0xcb,
	0x94, 0x61, 0x2c, 0x75, 0x52, 0xb8, 0xd6, 0xd1, 0x70, 0x57, 0x55, 0xd8, 0xc5, 0xa5, 0x19, 0x67,
	0x1a, 0xee, 0x19, 0xbd, 0x23, 0x35, 0xc3, 0x13, 0x71, 0x4e, 0x97, 0x65, 0xb4, 0x5f, 0xaa, 0xd9,
	0xc6, 0x6f, 0x14, 0x56, 0x6f, 0x37, 0x23, 0x1f, 0x3b, 0x16, 0xeb, 0x66, 0x7f, 0x80, 0x9b, 0xe9,
	0x78, 0xd4, 0x60, 0x33, 0x8d, 0x9f, 0xf6, 0x3b, 0x83, 0x2e, 0xcb, 0xaf, 0x25, 0x3b, 0x5a, 0xba,
	0x9a, 0x61, 0xf6, 0xa4, 0x71, 0x99, 0x4a, 0x6a, 0x96, 0xf9, 0x90, 0x66, 0xf1, 0xc8, 0xa8, 0xb9,
	0xc6, 0xaf, 0x15, 0x58, 0xe3, 0x33, 0xa1, 0x78, 0x44, 0xb9, 0x45, 0xdb, 0xb0, 0xa5, 0x75, 0x74,
	0x6c, 0xd9, 0x5a, 0xd3, 0x32, 0xfa, 0xbd, 0x94, 0x55, 0x8f, 0xa0, 0xb6, 0xc8, 0x13, 0x31, 0x55,
	0x95, 0xe5, 0xdc, 0x26, 0xd6, 0x35, 0x8b, 0xd9, 0xb7, 0x94, 0x3b, 0x38, 0x69, 0x31, 0x6e, 0xb6,
	0xf1, 0xcb, 0xf8, 0xd5, 0x4e, 0x8c, 0x33, 0x6c, 0x8b, 0x70, 0x3b, 0xde, 0x73, 0xa2, 0x61, 0xad,
	0x1b, 0x1b, 0xf3, 0x01, 0x3c, 0x58, 0xc6, 0xed, 0xb7, 0xdb, 0xaa, 0xc2, 0xbc, 0x58, 0xca, 0xec,
	0xa9, 0x99, 0xc6, 0x29, 0x14, 0x9b, 0x3e, 0xe5, 0xce, 0xae, 0x43, 0xb5, 0xd9, 0x4f, 0x57, 0x90,
	0x0a, 0x2b, 0x33, 0xa8, 0xd3, 0x3f, 0x53, 0x15, 0xb4, 0x01, 0x6b, 0x33, 0xa4, 0xab, 0xb7, 0x8c,
	0x41, 0x57, 0xcd, 0xa4, 0x76, 0x1e, 0x1b, 0x47, 0xc7, 0x6a, 0xb6, 0xf1, 0x6f, 0x05, 0x2a, 0x89,
	0xc1, 0x84, 0xd5, 0xaf, 0xb4, 0x81, 0xf5, 0x98, 0xe4, 0xd5, 0xa6, 0xe0, 0x13, 0xbd, 0xd7, 0x62,
	0x79, 0x93, 0x34, 0x5a, 0x70, 0xb4, 0x53, 0xcd, 0xe8, 0x68, 0x87, 0x1d, 0x79, 0xbd, 0x69, 0x9e,
	0x65, 0x69, 0xcd, 0x63, 0x96, 0xca, 0x0b, 0xac, 0x96, 0x2e, 0x59, 0xb9, 0x44, 0x8c, 0x6e, 0x58,
	0x56, 0xf3, 0x98, 0x1d, 0x97, 0x67, 0x99, 0x94, 0x62, 0x8a, 0x3e, 0x5a, 0x58, 0x30, 0x30, 0x2e,
	0x9a, 0x62, 0xe3, 0x77, 0x0a, 0xac, 0x24, 0xff, 0x2b, 0xcc, 0xa9, 0xb8, 0x69, 0xe8, 0x8f, 0xe1,
	0xe1, 0x3c, 0x6e, 0xd9, 0x27, 0x58, 0x37, 0xf5, 0x1e, 0x6b, 0xef, 0x9b, 0xa0, 0xa6, 0xd9, 0x83,
	0x13, 0xd1, 0x22, 0xd3, 0x68, 0xab, 0x7f, 0xd6, 0x53, 0xb3, 0x73, 0x61, 0xe1, 0x4d, 0xfc, 0x08,
	0x6b, 0xac, 0xd8, 0x73, 0x8d, 0x5f, 0x40, 0x35, 0xf5, 0x23, 0x9f, 0x79, 0x6c, 0x5a, 0x7d, 0xac,
	0x1d, 0xc5, 0x77, 0x65, 0x77, 0xb5, 0xa3, 0x9e, 0x6e, 0x19, 0x4d, 0xf5, 0x3d, 0xd1, 0xee, 0x53,
	0x4c, 0xd3, 0x64, 0x6d, 0x85, 0xbf, 0x0f, 0x29, 0xbc, 0x77, 0xda, 0xd5, 0xd5, 0x4c, 0x63, 0x17,
	0xaa, 0xf2, 0xc9, 0xef, 0xf9, 0x91, 0xfb, 0xfa, 0x9a, 0x49, 0xca, 0xba, 0x92, 0x45, 0x2d, 0x8c,
	0x7c, 0xef, 0xf0, 0x11, 0x6c, 0x0c, 0xfd, 0xc9, 0xfc, 0x93, 0x78, 0xa2, 0x7c, 0x95, 0x75, 0x02,
	0xf7, 0x55, 0x81, 0x7f, 0x4a, 0x7e, 0xef, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x15, 0xaa, 0x8e,
	0xe4, 0x10, 0x19, 0x00, 0x00,
}
