// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/clouddrive.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// CloudDriveSetState indicates the state of the DriveSet
type CloudDriveSetState int32

const (
	// Initializing indicates that the DriveSet is attached to a node but still in
	// init state
	CloudDriveSetState_initializing CloudDriveSetState = 0
	// Attached indicates that the DriveSet is attached and in use by a node
	CloudDriveSetState_attached CloudDriveSetState = 1
	// Detached indicates that the DriveSet is detached and not used by any node
	CloudDriveSetState_detached CloudDriveSetState = 2
	// PendingDecommission indicates that the DriveSet needs to be deleted
	CloudDriveSetState_pending_decommission CloudDriveSetState = 3
)

var CloudDriveSetState_name = map[int32]string{
	0: "initializing",
	1: "attached",
	2: "detached",
	3: "pending_decommission",
}
var CloudDriveSetState_value = map[string]int32{
	"initializing":         0,
	"attached":             1,
	"detached":             2,
	"pending_decommission": 3,
}

func (x CloudDriveSetState) String() string {
	return proto.EnumName(CloudDriveSetState_name, int32(x))
}
func (CloudDriveSetState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_clouddrive_66058428868e8fc0, []int{0}
}

// Defines the operation types available to expand a drive set
type DriveSetExpandOperationType int32

const (
	// Automatically pick the optimum operation type
	DriveSetExpandOperationType_Auto DriveSetExpandOperationType = 0
	// Add a new drive to expand the drive set
	DriveSetExpandOperationType_Add DriveSetExpandOperationType = 1
	// Resize existing drives to expand the drive set
	DriveSetExpandOperationType_Resize DriveSetExpandOperationType = 2
)

var DriveSetExpandOperationType_name = map[int32]string{
	0: "Auto",
	1: "Add",
	2: "Resize",
}
var DriveSetExpandOperationType_value = map[string]int32{
	"Auto":   0,
	"Add":    1,
	"Resize": 2,
}

func (x DriveSetExpandOperationType) String() string {
	return proto.EnumName(DriveSetExpandOperationType_name, int32(x))
}
func (DriveSetExpandOperationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_clouddrive_66058428868e8fc0, []int{1}
}

// CloudDriveSet defines a set of storage  pools that could be attached on a node
type CloudDriveSet struct {
	// ID is the unique id of the cloud drive. This is managed by the storage provider
	// implementing the handlers
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// Pools describes the configuration of the drives present in this set
	Pools []*StoragePool `protobuf:"bytes,2,rep,name=pools" json:"pools,omitempty"`
	// CreateTimestamp is the timestamp when the drive set was created
	CreateTimestamp *timestamp.Timestamp `protobuf:"bytes,3,opt,name=create_timestamp,json=createTimestamp" json:"create_timestamp,omitempty"`
	// State state of the drive set from the well defined states
	State CloudDriveSetState `protobuf:"varint,4,opt,name=state,enum=openstorage.api.CloudDriveSetState" json:"state,omitempty"`
	// InstanceName is the name of the node  who is using the drive set
	InstanceName string `protobuf:"bytes,5,opt,name=instance_name,json=instanceName" json:"instance_name,omitempty"`
	// InstanceID is the cloud provider id of the instance using this drive set
	InstanceId string `protobuf:"bytes,6,opt,name=instance_id,json=instanceId" json:"instance_id,omitempty"`
	// Zone defines the zone in which the node exists
	Zone                 string   `protobuf:"bytes,7,opt,name=zone" json:"zone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloudDriveSet) Reset()         { *m = CloudDriveSet{} }
func (m *CloudDriveSet) String() string { return proto.CompactTextString(m) }
func (*CloudDriveSet) ProtoMessage()    {}
func (*CloudDriveSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_clouddrive_66058428868e8fc0, []int{0}
}
func (m *CloudDriveSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloudDriveSet.Unmarshal(m, b)
}
func (m *CloudDriveSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloudDriveSet.Marshal(b, m, deterministic)
}
func (dst *CloudDriveSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloudDriveSet.Merge(dst, src)
}
func (m *CloudDriveSet) XXX_Size() int {
	return xxx_messageInfo_CloudDriveSet.Size(m)
}
func (m *CloudDriveSet) XXX_DiscardUnknown() {
	xxx_messageInfo_CloudDriveSet.DiscardUnknown(m)
}

var xxx_messageInfo_CloudDriveSet proto.InternalMessageInfo

func (m *CloudDriveSet) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CloudDriveSet) GetPools() []*StoragePool {
	if m != nil {
		return m.Pools
	}
	return nil
}

func (m *CloudDriveSet) GetCreateTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTimestamp
	}
	return nil
}

func (m *CloudDriveSet) GetState() CloudDriveSetState {
	if m != nil {
		return m.State
	}
	return CloudDriveSetState_initializing
}

func (m *CloudDriveSet) GetInstanceName() string {
	if m != nil {
		return m.InstanceName
	}
	return ""
}

func (m *CloudDriveSet) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

func (m *CloudDriveSet) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

// Request to create the drive set
type SdkCloudDriveSetCreateRequest struct {
	// Specs are the list of specs for the cloud drives to create. For each item
	// in the list, a drive will be created and added to the CloudDriveSet
	Specs                []*CloudDriveSpec `protobuf:"bytes,1,rep,name=specs" json:"specs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SdkCloudDriveSetCreateRequest) Reset()         { *m = SdkCloudDriveSetCreateRequest{} }
func (m *SdkCloudDriveSetCreateRequest) String() string { return proto.CompactTextString(m) }
func (*SdkCloudDriveSetCreateRequest) ProtoMessage()    {}
func (*SdkCloudDriveSetCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_clouddrive_66058428868e8fc0, []int{1}
}
func (m *SdkCloudDriveSetCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SdkCloudDriveSetCreateRequest.Unmarshal(m, b)
}
func (m *SdkCloudDriveSetCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SdkCloudDriveSetCreateRequest.Marshal(b, m, deterministic)
}
func (dst *SdkCloudDriveSetCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SdkCloudDriveSetCreateRequest.Merge(dst, src)
}
func (m *SdkCloudDriveSetCreateRequest) XXX_Size() int {
	return xxx_messageInfo_SdkCloudDriveSetCreateRequest.Size(m)
}
func (m *SdkCloudDriveSetCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SdkCloudDriveSetCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SdkCloudDriveSetCreateRequest proto.InternalMessageInfo

func (m *SdkCloudDriveSetCreateRequest) GetSpecs() []*CloudDriveSpec {
	if m != nil {
		return m.Specs
	}
	return nil
}

// CloudDriveSpec is a spec for a CloudDrive
type CloudDriveSpec struct {
	// Size is the required size of the CloudDrive
	Size int64 `protobuf:"varint,1,opt,name=size" json:"size,omitempty"`
	// Type is the type of the CloudDrive
	Type string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	// Options are other opaque key value pair options
	Options              map[string]string `protobuf:"bytes,3,rep,name=options" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CloudDriveSpec) Reset()         { *m = CloudDriveSpec{} }
func (m *CloudDriveSpec) String() string { return proto.CompactTextString(m) }
func (*CloudDriveSpec) ProtoMessage()    {}
func (*CloudDriveSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_clouddrive_66058428868e8fc0, []int{2}
}
func (m *CloudDriveSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloudDriveSpec.Unmarshal(m, b)
}
func (m *CloudDriveSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloudDriveSpec.Marshal(b, m, deterministic)
}
func (dst *CloudDriveSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloudDriveSpec.Merge(dst, src)
}
func (m *CloudDriveSpec) XXX_Size() int {
	return xxx_messageInfo_CloudDriveSpec.Size(m)
}
func (m *CloudDriveSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_CloudDriveSpec.DiscardUnknown(m)
}

var xxx_messageInfo_CloudDriveSpec proto.InternalMessageInfo

func (m *CloudDriveSpec) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *CloudDriveSpec) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CloudDriveSpec) GetOptions() map[string]string {
	if m != nil {
		return m.Options
	}
	return nil
}

// Defines a response with a list of cloud drives
type SdkCloudDriveSetCreateResponse struct {
	// CloudDriveSet that's created for this create request
	CloudDriveSet        *CloudDriveSet `protobuf:"bytes,1,opt,name=cloud_drive_set,json=cloudDriveSet" json:"cloud_drive_set,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SdkCloudDriveSetCreateResponse) Reset()         { *m = SdkCloudDriveSetCreateResponse{} }
func (m *SdkCloudDriveSetCreateResponse) String() string { return proto.CompactTextString(m) }
func (*SdkCloudDriveSetCreateResponse) ProtoMessage()    {}
func (*SdkCloudDriveSetCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_clouddrive_66058428868e8fc0, []int{3}
}
func (m *SdkCloudDriveSetCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SdkCloudDriveSetCreateResponse.Unmarshal(m, b)
}
func (m *SdkCloudDriveSetCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SdkCloudDriveSetCreateResponse.Marshal(b, m, deterministic)
}
func (dst *SdkCloudDriveSetCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SdkCloudDriveSetCreateResponse.Merge(dst, src)
}
func (m *SdkCloudDriveSetCreateResponse) XXX_Size() int {
	return xxx_messageInfo_SdkCloudDriveSetCreateResponse.Size(m)
}
func (m *SdkCloudDriveSetCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SdkCloudDriveSetCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SdkCloudDriveSetCreateResponse proto.InternalMessageInfo

func (m *SdkCloudDriveSetCreateResponse) GetCloudDriveSet() *CloudDriveSet {
	if m != nil {
		return m.CloudDriveSet
	}
	return nil
}

// Empty request
type SdkCloudDriveSetEnumerateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SdkCloudDriveSetEnumerateRequest) Reset()         { *m = SdkCloudDriveSetEnumerateRequest{} }
func (m *SdkCloudDriveSetEnumerateRequest) String() string { return proto.CompactTextString(m) }
func (*SdkCloudDriveSetEnumerateRequest) ProtoMessage()    {}
func (*SdkCloudDriveSetEnumerateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_clouddrive_66058428868e8fc0, []int{4}
}
func (m *SdkCloudDriveSetEnumerateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SdkCloudDriveSetEnumerateRequest.Unmarshal(m, b)
}
func (m *SdkCloudDriveSetEnumerateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SdkCloudDriveSetEnumerateRequest.Marshal(b, m, deterministic)
}
func (dst *SdkCloudDriveSetEnumerateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SdkCloudDriveSetEnumerateRequest.Merge(dst, src)
}
func (m *SdkCloudDriveSetEnumerateRequest) XXX_Size() int {
	return xxx_messageInfo_SdkCloudDriveSetEnumerateRequest.Size(m)
}
func (m *SdkCloudDriveSetEnumerateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SdkCloudDriveSetEnumerateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SdkCloudDriveSetEnumerateRequest proto.InternalMessageInfo

// Defines a response with a list of cloud drives
type SdkCloudDriveSetEnumerateResponse struct {
	// List of all the cloud drive sets in the cluster
	CloudDriveSets       []*CloudDriveSet `protobuf:"bytes,1,rep,name=cloud_drive_sets,json=cloudDriveSets" json:"cloud_drive_sets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SdkCloudDriveSetEnumerateResponse) Reset()         { *m = SdkCloudDriveSetEnumerateResponse{} }
func (m *SdkCloudDriveSetEnumerateResponse) String() string { return proto.CompactTextString(m) }
func (*SdkCloudDriveSetEnumerateResponse) ProtoMessage()    {}
func (*SdkCloudDriveSetEnumerateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_clouddrive_66058428868e8fc0, []int{5}
}
func (m *SdkCloudDriveSetEnumerateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SdkCloudDriveSetEnumerateResponse.Unmarshal(m, b)
}
func (m *SdkCloudDriveSetEnumerateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SdkCloudDriveSetEnumerateResponse.Marshal(b, m, deterministic)
}
func (dst *SdkCloudDriveSetEnumerateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SdkCloudDriveSetEnumerateResponse.Merge(dst, src)
}
func (m *SdkCloudDriveSetEnumerateResponse) XXX_Size() int {
	return xxx_messageInfo_SdkCloudDriveSetEnumerateResponse.Size(m)
}
func (m *SdkCloudDriveSetEnumerateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SdkCloudDriveSetEnumerateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SdkCloudDriveSetEnumerateResponse proto.InternalMessageInfo

func (m *SdkCloudDriveSetEnumerateResponse) GetCloudDriveSets() []*CloudDriveSet {
	if m != nil {
		return m.CloudDriveSets
	}
	return nil
}

// Defines a request object to inspect a cloud drive
type SdkCloudDriveSetInspectRequest struct {
	// ID of the cloud drive to inspect
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SdkCloudDriveSetInspectRequest) Reset()         { *m = SdkCloudDriveSetInspectRequest{} }
func (m *SdkCloudDriveSetInspectRequest) String() string { return proto.CompactTextString(m) }
func (*SdkCloudDriveSetInspectRequest) ProtoMessage()    {}
func (*SdkCloudDriveSetInspectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_clouddrive_66058428868e8fc0, []int{6}
}
func (m *SdkCloudDriveSetInspectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SdkCloudDriveSetInspectRequest.Unmarshal(m, b)
}
func (m *SdkCloudDriveSetInspectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SdkCloudDriveSetInspectRequest.Marshal(b, m, deterministic)
}
func (dst *SdkCloudDriveSetInspectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SdkCloudDriveSetInspectRequest.Merge(dst, src)
}
func (m *SdkCloudDriveSetInspectRequest) XXX_Size() int {
	return xxx_messageInfo_SdkCloudDriveSetInspectRequest.Size(m)
}
func (m *SdkCloudDriveSetInspectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SdkCloudDriveSetInspectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SdkCloudDriveSetInspectRequest proto.InternalMessageInfo

func (m *SdkCloudDriveSetInspectRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Defines a response for the inspect cloud drive operation
type SdkCloudDriveSetInspectResponse struct {
	// CloudDrive that was requested to inspect
	CloudDriveSet        *CloudDriveSet `protobuf:"bytes,1,opt,name=cloud_drive_set,json=cloudDriveSet" json:"cloud_drive_set,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SdkCloudDriveSetInspectResponse) Reset()         { *m = SdkCloudDriveSetInspectResponse{} }
func (m *SdkCloudDriveSetInspectResponse) String() string { return proto.CompactTextString(m) }
func (*SdkCloudDriveSetInspectResponse) ProtoMessage()    {}
func (*SdkCloudDriveSetInspectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_clouddrive_66058428868e8fc0, []int{7}
}
func (m *SdkCloudDriveSetInspectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SdkCloudDriveSetInspectResponse.Unmarshal(m, b)
}
func (m *SdkCloudDriveSetInspectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SdkCloudDriveSetInspectResponse.Marshal(b, m, deterministic)
}
func (dst *SdkCloudDriveSetInspectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SdkCloudDriveSetInspectResponse.Merge(dst, src)
}
func (m *SdkCloudDriveSetInspectResponse) XXX_Size() int {
	return xxx_messageInfo_SdkCloudDriveSetInspectResponse.Size(m)
}
func (m *SdkCloudDriveSetInspectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SdkCloudDriveSetInspectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SdkCloudDriveSetInspectResponse proto.InternalMessageInfo

func (m *SdkCloudDriveSetInspectResponse) GetCloudDriveSet() *CloudDriveSet {
	if m != nil {
		return m.CloudDriveSet
	}
	return nil
}

// Defines a request object to delete a cloud drive
type SdkCloudDriveSetDeleteRequest struct {
	// ID of the cloud drive to delete
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SdkCloudDriveSetDeleteRequest) Reset()         { *m = SdkCloudDriveSetDeleteRequest{} }
func (m *SdkCloudDriveSetDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*SdkCloudDriveSetDeleteRequest) ProtoMessage()    {}
func (*SdkCloudDriveSetDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_clouddrive_66058428868e8fc0, []int{8}
}
func (m *SdkCloudDriveSetDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SdkCloudDriveSetDeleteRequest.Unmarshal(m, b)
}
func (m *SdkCloudDriveSetDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SdkCloudDriveSetDeleteRequest.Marshal(b, m, deterministic)
}
func (dst *SdkCloudDriveSetDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SdkCloudDriveSetDeleteRequest.Merge(dst, src)
}
func (m *SdkCloudDriveSetDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_SdkCloudDriveSetDeleteRequest.Size(m)
}
func (m *SdkCloudDriveSetDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SdkCloudDriveSetDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SdkCloudDriveSetDeleteRequest proto.InternalMessageInfo

func (m *SdkCloudDriveSetDeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Empty response
type SdkCloudDriveSetDeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SdkCloudDriveSetDeleteResponse) Reset()         { *m = SdkCloudDriveSetDeleteResponse{} }
func (m *SdkCloudDriveSetDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*SdkCloudDriveSetDeleteResponse) ProtoMessage()    {}
func (*SdkCloudDriveSetDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_clouddrive_66058428868e8fc0, []int{9}
}
func (m *SdkCloudDriveSetDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SdkCloudDriveSetDeleteResponse.Unmarshal(m, b)
}
func (m *SdkCloudDriveSetDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SdkCloudDriveSetDeleteResponse.Marshal(b, m, deterministic)
}
func (dst *SdkCloudDriveSetDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SdkCloudDriveSetDeleteResponse.Merge(dst, src)
}
func (m *SdkCloudDriveSetDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_SdkCloudDriveSetDeleteResponse.Size(m)
}
func (m *SdkCloudDriveSetDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SdkCloudDriveSetDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SdkCloudDriveSetDeleteResponse proto.InternalMessageInfo

// Defines a request object to a cloud drive
type SdkCloudDriveSetAttachRequest struct {
	// ID of the cloud drive to attach
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// InstanceID of the node to attach the drive set
	InstanceId           string   `protobuf:"bytes,2,opt,name=instance_id,json=instanceId" json:"instance_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SdkCloudDriveSetAttachRequest) Reset()         { *m = SdkCloudDriveSetAttachRequest{} }
func (m *SdkCloudDriveSetAttachRequest) String() string { return proto.CompactTextString(m) }
func (*SdkCloudDriveSetAttachRequest) ProtoMessage()    {}
func (*SdkCloudDriveSetAttachRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_clouddrive_66058428868e8fc0, []int{10}
}
func (m *SdkCloudDriveSetAttachRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SdkCloudDriveSetAttachRequest.Unmarshal(m, b)
}
func (m *SdkCloudDriveSetAttachRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SdkCloudDriveSetAttachRequest.Marshal(b, m, deterministic)
}
func (dst *SdkCloudDriveSetAttachRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SdkCloudDriveSetAttachRequest.Merge(dst, src)
}
func (m *SdkCloudDriveSetAttachRequest) XXX_Size() int {
	return xxx_messageInfo_SdkCloudDriveSetAttachRequest.Size(m)
}
func (m *SdkCloudDriveSetAttachRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SdkCloudDriveSetAttachRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SdkCloudDriveSetAttachRequest proto.InternalMessageInfo

func (m *SdkCloudDriveSetAttachRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SdkCloudDriveSetAttachRequest) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

// Defines a response for the attach cloud drive operation
type SdkCloudDriveSetAttachResponse struct {
	// AttachedDrives is the list of the drives that are attached
	AttachedDrives       []*AttachedCloudDrive `protobuf:"bytes,1,rep,name=attached_drives,json=attachedDrives" json:"attached_drives,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SdkCloudDriveSetAttachResponse) Reset()         { *m = SdkCloudDriveSetAttachResponse{} }
func (m *SdkCloudDriveSetAttachResponse) String() string { return proto.CompactTextString(m) }
func (*SdkCloudDriveSetAttachResponse) ProtoMessage()    {}
func (*SdkCloudDriveSetAttachResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_clouddrive_66058428868e8fc0, []int{11}
}
func (m *SdkCloudDriveSetAttachResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SdkCloudDriveSetAttachResponse.Unmarshal(m, b)
}
func (m *SdkCloudDriveSetAttachResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SdkCloudDriveSetAttachResponse.Marshal(b, m, deterministic)
}
func (dst *SdkCloudDriveSetAttachResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SdkCloudDriveSetAttachResponse.Merge(dst, src)
}
func (m *SdkCloudDriveSetAttachResponse) XXX_Size() int {
	return xxx_messageInfo_SdkCloudDriveSetAttachResponse.Size(m)
}
func (m *SdkCloudDriveSetAttachResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SdkCloudDriveSetAttachResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SdkCloudDriveSetAttachResponse proto.InternalMessageInfo

func (m *SdkCloudDriveSetAttachResponse) GetAttachedDrives() []*AttachedCloudDrive {
	if m != nil {
		return m.AttachedDrives
	}
	return nil
}

// CloudDriveAttachedDrive represents a single attached drive
type AttachedCloudDrive struct {
	// ID is the ID of the drive that's attached
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// Path is the path where the drive is attached
	Path                 string   `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachedCloudDrive) Reset()         { *m = AttachedCloudDrive{} }
func (m *AttachedCloudDrive) String() string { return proto.CompactTextString(m) }
func (*AttachedCloudDrive) ProtoMessage()    {}
func (*AttachedCloudDrive) Descriptor() ([]byte, []int) {
	return fileDescriptor_clouddrive_66058428868e8fc0, []int{12}
}
func (m *AttachedCloudDrive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachedCloudDrive.Unmarshal(m, b)
}
func (m *AttachedCloudDrive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachedCloudDrive.Marshal(b, m, deterministic)
}
func (dst *AttachedCloudDrive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachedCloudDrive.Merge(dst, src)
}
func (m *AttachedCloudDrive) XXX_Size() int {
	return xxx_messageInfo_AttachedCloudDrive.Size(m)
}
func (m *AttachedCloudDrive) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachedCloudDrive.DiscardUnknown(m)
}

var xxx_messageInfo_AttachedCloudDrive proto.InternalMessageInfo

func (m *AttachedCloudDrive) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AttachedCloudDrive) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

// Defines a request object to detach a cloud drive
type SdkCloudDriveSetDetachRequest struct {
	// ID of the cloud drive to detach
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SdkCloudDriveSetDetachRequest) Reset()         { *m = SdkCloudDriveSetDetachRequest{} }
func (m *SdkCloudDriveSetDetachRequest) String() string { return proto.CompactTextString(m) }
func (*SdkCloudDriveSetDetachRequest) ProtoMessage()    {}
func (*SdkCloudDriveSetDetachRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_clouddrive_66058428868e8fc0, []int{13}
}
func (m *SdkCloudDriveSetDetachRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SdkCloudDriveSetDetachRequest.Unmarshal(m, b)
}
func (m *SdkCloudDriveSetDetachRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SdkCloudDriveSetDetachRequest.Marshal(b, m, deterministic)
}
func (dst *SdkCloudDriveSetDetachRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SdkCloudDriveSetDetachRequest.Merge(dst, src)
}
func (m *SdkCloudDriveSetDetachRequest) XXX_Size() int {
	return xxx_messageInfo_SdkCloudDriveSetDetachRequest.Size(m)
}
func (m *SdkCloudDriveSetDetachRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SdkCloudDriveSetDetachRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SdkCloudDriveSetDetachRequest proto.InternalMessageInfo

func (m *SdkCloudDriveSetDetachRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Empty response
type SdkCloudDriveSetDetachResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SdkCloudDriveSetDetachResponse) Reset()         { *m = SdkCloudDriveSetDetachResponse{} }
func (m *SdkCloudDriveSetDetachResponse) String() string { return proto.CompactTextString(m) }
func (*SdkCloudDriveSetDetachResponse) ProtoMessage()    {}
func (*SdkCloudDriveSetDetachResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_clouddrive_66058428868e8fc0, []int{14}
}
func (m *SdkCloudDriveSetDetachResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SdkCloudDriveSetDetachResponse.Unmarshal(m, b)
}
func (m *SdkCloudDriveSetDetachResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SdkCloudDriveSetDetachResponse.Marshal(b, m, deterministic)
}
func (dst *SdkCloudDriveSetDetachResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SdkCloudDriveSetDetachResponse.Merge(dst, src)
}
func (m *SdkCloudDriveSetDetachResponse) XXX_Size() int {
	return xxx_messageInfo_SdkCloudDriveSetDetachResponse.Size(m)
}
func (m *SdkCloudDriveSetDetachResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SdkCloudDriveSetDetachResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SdkCloudDriveSetDetachResponse proto.InternalMessageInfo

// Defines a request object to expand a cloud drive
type SdkCloudDriveSetExpandRequest struct {
	// ID of the cloud drive set to expand
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// PoolID of the pool inside the cloud drive to expand
	PoolId string `protobuf:"bytes,2,opt,name=pool_id,json=poolId" json:"pool_id,omitempty"`
	// OperationType is the operation that's used to expand the drive set (optional)
	OperationType        DriveSetExpandOperationType `protobuf:"varint,3,opt,name=operation_type,json=operationType,enum=openstorage.api.DriveSetExpandOperationType" json:"operation_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *SdkCloudDriveSetExpandRequest) Reset()         { *m = SdkCloudDriveSetExpandRequest{} }
func (m *SdkCloudDriveSetExpandRequest) String() string { return proto.CompactTextString(m) }
func (*SdkCloudDriveSetExpandRequest) ProtoMessage()    {}
func (*SdkCloudDriveSetExpandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_clouddrive_66058428868e8fc0, []int{15}
}
func (m *SdkCloudDriveSetExpandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SdkCloudDriveSetExpandRequest.Unmarshal(m, b)
}
func (m *SdkCloudDriveSetExpandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SdkCloudDriveSetExpandRequest.Marshal(b, m, deterministic)
}
func (dst *SdkCloudDriveSetExpandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SdkCloudDriveSetExpandRequest.Merge(dst, src)
}
func (m *SdkCloudDriveSetExpandRequest) XXX_Size() int {
	return xxx_messageInfo_SdkCloudDriveSetExpandRequest.Size(m)
}
func (m *SdkCloudDriveSetExpandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SdkCloudDriveSetExpandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SdkCloudDriveSetExpandRequest proto.InternalMessageInfo

func (m *SdkCloudDriveSetExpandRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SdkCloudDriveSetExpandRequest) GetPoolId() string {
	if m != nil {
		return m.PoolId
	}
	return ""
}

func (m *SdkCloudDriveSetExpandRequest) GetOperationType() DriveSetExpandOperationType {
	if m != nil {
		return m.OperationType
	}
	return DriveSetExpandOperationType_Auto
}

// Defines a response for the inspect cloud drive operation
type SdkCloudDriveSetExpandResponse struct {
	// CloudDriveSet that was requested to expand
	CloudDriveSet        *CloudDriveSet `protobuf:"bytes,1,opt,name=cloud_drive_set,json=cloudDriveSet" json:"cloud_drive_set,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SdkCloudDriveSetExpandResponse) Reset()         { *m = SdkCloudDriveSetExpandResponse{} }
func (m *SdkCloudDriveSetExpandResponse) String() string { return proto.CompactTextString(m) }
func (*SdkCloudDriveSetExpandResponse) ProtoMessage()    {}
func (*SdkCloudDriveSetExpandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_clouddrive_66058428868e8fc0, []int{16}
}
func (m *SdkCloudDriveSetExpandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SdkCloudDriveSetExpandResponse.Unmarshal(m, b)
}
func (m *SdkCloudDriveSetExpandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SdkCloudDriveSetExpandResponse.Marshal(b, m, deterministic)
}
func (dst *SdkCloudDriveSetExpandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SdkCloudDriveSetExpandResponse.Merge(dst, src)
}
func (m *SdkCloudDriveSetExpandResponse) XXX_Size() int {
	return xxx_messageInfo_SdkCloudDriveSetExpandResponse.Size(m)
}
func (m *SdkCloudDriveSetExpandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SdkCloudDriveSetExpandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SdkCloudDriveSetExpandResponse proto.InternalMessageInfo

func (m *SdkCloudDriveSetExpandResponse) GetCloudDriveSet() *CloudDriveSet {
	if m != nil {
		return m.CloudDriveSet
	}
	return nil
}

func init() {
	proto.RegisterType((*CloudDriveSet)(nil), "openstorage.api.CloudDriveSet")
	proto.RegisterType((*SdkCloudDriveSetCreateRequest)(nil), "openstorage.api.SdkCloudDriveSetCreateRequest")
	proto.RegisterType((*CloudDriveSpec)(nil), "openstorage.api.CloudDriveSpec")
	proto.RegisterMapType((map[string]string)(nil), "openstorage.api.CloudDriveSpec.OptionsEntry")
	proto.RegisterType((*SdkCloudDriveSetCreateResponse)(nil), "openstorage.api.SdkCloudDriveSetCreateResponse")
	proto.RegisterType((*SdkCloudDriveSetEnumerateRequest)(nil), "openstorage.api.SdkCloudDriveSetEnumerateRequest")
	proto.RegisterType((*SdkCloudDriveSetEnumerateResponse)(nil), "openstorage.api.SdkCloudDriveSetEnumerateResponse")
	proto.RegisterType((*SdkCloudDriveSetInspectRequest)(nil), "openstorage.api.SdkCloudDriveSetInspectRequest")
	proto.RegisterType((*SdkCloudDriveSetInspectResponse)(nil), "openstorage.api.SdkCloudDriveSetInspectResponse")
	proto.RegisterType((*SdkCloudDriveSetDeleteRequest)(nil), "openstorage.api.SdkCloudDriveSetDeleteRequest")
	proto.RegisterType((*SdkCloudDriveSetDeleteResponse)(nil), "openstorage.api.SdkCloudDriveSetDeleteResponse")
	proto.RegisterType((*SdkCloudDriveSetAttachRequest)(nil), "openstorage.api.SdkCloudDriveSetAttachRequest")
	proto.RegisterType((*SdkCloudDriveSetAttachResponse)(nil), "openstorage.api.SdkCloudDriveSetAttachResponse")
	proto.RegisterType((*AttachedCloudDrive)(nil), "openstorage.api.AttachedCloudDrive")
	proto.RegisterType((*SdkCloudDriveSetDetachRequest)(nil), "openstorage.api.SdkCloudDriveSetDetachRequest")
	proto.RegisterType((*SdkCloudDriveSetDetachResponse)(nil), "openstorage.api.SdkCloudDriveSetDetachResponse")
	proto.RegisterType((*SdkCloudDriveSetExpandRequest)(nil), "openstorage.api.SdkCloudDriveSetExpandRequest")
	proto.RegisterType((*SdkCloudDriveSetExpandResponse)(nil), "openstorage.api.SdkCloudDriveSetExpandResponse")
	proto.RegisterEnum("openstorage.api.CloudDriveSetState", CloudDriveSetState_name, CloudDriveSetState_value)
	proto.RegisterEnum("openstorage.api.DriveSetExpandOperationType", DriveSetExpandOperationType_name, DriveSetExpandOperationType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for OpenStorageCloudDrives service

type OpenStorageCloudDrivesClient interface {
	// Enumerate returns the ids of all the cloud drives in the current cluster
	Enumerate(ctx context.Context, in *SdkCloudDriveSetEnumerateRequest, opts ...grpc.CallOption) (*SdkCloudDriveSetEnumerateResponse, error)
	// Create creates a new drive set
	Create(ctx context.Context, in *SdkCloudDriveSetCreateRequest, opts ...grpc.CallOption) (*SdkCloudDriveSetCreateResponse, error)
	// Expand expands the given drive set
	Expand(ctx context.Context, in *SdkCloudDriveSetExpandRequest, opts ...grpc.CallOption) (*SdkCloudDriveSetExpandResponse, error)
	// Delete deletes the given drive set
	Delete(ctx context.Context, in *SdkCloudDriveSetDeleteRequest, opts ...grpc.CallOption) (*SdkCloudDriveSetDeleteResponse, error)
	// Delete inspects the given drive set
	Inspect(ctx context.Context, in *SdkCloudDriveSetInspectRequest, opts ...grpc.CallOption) (*SdkCloudDriveSetInspectResponse, error)
	// Attach attaches all the drives in the given drive set to a single instance
	// provided in the request
	Attach(ctx context.Context, in *SdkCloudDriveSetAttachRequest, opts ...grpc.CallOption) (*SdkCloudDriveSetAttachResponse, error)
	// Detach detaches all the drives in the given drive set from the instance
	// where it's currently attached
	Detach(ctx context.Context, in *SdkCloudDriveSetDetachRequest, opts ...grpc.CallOption) (*SdkCloudDriveSetDetachResponse, error)
}

type openStorageCloudDrivesClient struct {
	cc *grpc.ClientConn
}

func NewOpenStorageCloudDrivesClient(cc *grpc.ClientConn) OpenStorageCloudDrivesClient {
	return &openStorageCloudDrivesClient{cc}
}

func (c *openStorageCloudDrivesClient) Enumerate(ctx context.Context, in *SdkCloudDriveSetEnumerateRequest, opts ...grpc.CallOption) (*SdkCloudDriveSetEnumerateResponse, error) {
	out := new(SdkCloudDriveSetEnumerateResponse)
	err := grpc.Invoke(ctx, "/openstorage.api.OpenStorageCloudDrives/Enumerate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openStorageCloudDrivesClient) Create(ctx context.Context, in *SdkCloudDriveSetCreateRequest, opts ...grpc.CallOption) (*SdkCloudDriveSetCreateResponse, error) {
	out := new(SdkCloudDriveSetCreateResponse)
	err := grpc.Invoke(ctx, "/openstorage.api.OpenStorageCloudDrives/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openStorageCloudDrivesClient) Expand(ctx context.Context, in *SdkCloudDriveSetExpandRequest, opts ...grpc.CallOption) (*SdkCloudDriveSetExpandResponse, error) {
	out := new(SdkCloudDriveSetExpandResponse)
	err := grpc.Invoke(ctx, "/openstorage.api.OpenStorageCloudDrives/Expand", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openStorageCloudDrivesClient) Delete(ctx context.Context, in *SdkCloudDriveSetDeleteRequest, opts ...grpc.CallOption) (*SdkCloudDriveSetDeleteResponse, error) {
	out := new(SdkCloudDriveSetDeleteResponse)
	err := grpc.Invoke(ctx, "/openstorage.api.OpenStorageCloudDrives/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openStorageCloudDrivesClient) Inspect(ctx context.Context, in *SdkCloudDriveSetInspectRequest, opts ...grpc.CallOption) (*SdkCloudDriveSetInspectResponse, error) {
	out := new(SdkCloudDriveSetInspectResponse)
	err := grpc.Invoke(ctx, "/openstorage.api.OpenStorageCloudDrives/Inspect", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openStorageCloudDrivesClient) Attach(ctx context.Context, in *SdkCloudDriveSetAttachRequest, opts ...grpc.CallOption) (*SdkCloudDriveSetAttachResponse, error) {
	out := new(SdkCloudDriveSetAttachResponse)
	err := grpc.Invoke(ctx, "/openstorage.api.OpenStorageCloudDrives/Attach", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openStorageCloudDrivesClient) Detach(ctx context.Context, in *SdkCloudDriveSetDetachRequest, opts ...grpc.CallOption) (*SdkCloudDriveSetDetachResponse, error) {
	out := new(SdkCloudDriveSetDetachResponse)
	err := grpc.Invoke(ctx, "/openstorage.api.OpenStorageCloudDrives/Detach", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OpenStorageCloudDrives service

type OpenStorageCloudDrivesServer interface {
	// Enumerate returns the ids of all the cloud drives in the current cluster
	Enumerate(context.Context, *SdkCloudDriveSetEnumerateRequest) (*SdkCloudDriveSetEnumerateResponse, error)
	// Create creates a new drive set
	Create(context.Context, *SdkCloudDriveSetCreateRequest) (*SdkCloudDriveSetCreateResponse, error)
	// Expand expands the given drive set
	Expand(context.Context, *SdkCloudDriveSetExpandRequest) (*SdkCloudDriveSetExpandResponse, error)
	// Delete deletes the given drive set
	Delete(context.Context, *SdkCloudDriveSetDeleteRequest) (*SdkCloudDriveSetDeleteResponse, error)
	// Delete inspects the given drive set
	Inspect(context.Context, *SdkCloudDriveSetInspectRequest) (*SdkCloudDriveSetInspectResponse, error)
	// Attach attaches all the drives in the given drive set to a single instance
	// provided in the request
	Attach(context.Context, *SdkCloudDriveSetAttachRequest) (*SdkCloudDriveSetAttachResponse, error)
	// Detach detaches all the drives in the given drive set from the instance
	// where it's currently attached
	Detach(context.Context, *SdkCloudDriveSetDetachRequest) (*SdkCloudDriveSetDetachResponse, error)
}

func RegisterOpenStorageCloudDrivesServer(s *grpc.Server, srv OpenStorageCloudDrivesServer) {
	s.RegisterService(&_OpenStorageCloudDrives_serviceDesc, srv)
}

func _OpenStorageCloudDrives_Enumerate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SdkCloudDriveSetEnumerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenStorageCloudDrivesServer).Enumerate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openstorage.api.OpenStorageCloudDrives/Enumerate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenStorageCloudDrivesServer).Enumerate(ctx, req.(*SdkCloudDriveSetEnumerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenStorageCloudDrives_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SdkCloudDriveSetCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenStorageCloudDrivesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openstorage.api.OpenStorageCloudDrives/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenStorageCloudDrivesServer).Create(ctx, req.(*SdkCloudDriveSetCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenStorageCloudDrives_Expand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SdkCloudDriveSetExpandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenStorageCloudDrivesServer).Expand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openstorage.api.OpenStorageCloudDrives/Expand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenStorageCloudDrivesServer).Expand(ctx, req.(*SdkCloudDriveSetExpandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenStorageCloudDrives_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SdkCloudDriveSetDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenStorageCloudDrivesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openstorage.api.OpenStorageCloudDrives/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenStorageCloudDrivesServer).Delete(ctx, req.(*SdkCloudDriveSetDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenStorageCloudDrives_Inspect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SdkCloudDriveSetInspectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenStorageCloudDrivesServer).Inspect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openstorage.api.OpenStorageCloudDrives/Inspect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenStorageCloudDrivesServer).Inspect(ctx, req.(*SdkCloudDriveSetInspectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenStorageCloudDrives_Attach_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SdkCloudDriveSetAttachRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenStorageCloudDrivesServer).Attach(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openstorage.api.OpenStorageCloudDrives/Attach",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenStorageCloudDrivesServer).Attach(ctx, req.(*SdkCloudDriveSetAttachRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenStorageCloudDrives_Detach_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SdkCloudDriveSetDetachRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenStorageCloudDrivesServer).Detach(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openstorage.api.OpenStorageCloudDrives/Detach",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenStorageCloudDrivesServer).Detach(ctx, req.(*SdkCloudDriveSetDetachRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OpenStorageCloudDrives_serviceDesc = grpc.ServiceDesc{
	ServiceName: "openstorage.api.OpenStorageCloudDrives",
	HandlerType: (*OpenStorageCloudDrivesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enumerate",
			Handler:    _OpenStorageCloudDrives_Enumerate_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _OpenStorageCloudDrives_Create_Handler,
		},
		{
			MethodName: "Expand",
			Handler:    _OpenStorageCloudDrives_Expand_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _OpenStorageCloudDrives_Delete_Handler,
		},
		{
			MethodName: "Inspect",
			Handler:    _OpenStorageCloudDrives_Inspect_Handler,
		},
		{
			MethodName: "Attach",
			Handler:    _OpenStorageCloudDrives_Attach_Handler,
		},
		{
			MethodName: "Detach",
			Handler:    _OpenStorageCloudDrives_Detach_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/clouddrive.proto",
}

func init() { proto.RegisterFile("api/clouddrive.proto", fileDescriptor_clouddrive_66058428868e8fc0) }

var fileDescriptor_clouddrive_66058428868e8fc0 = []byte{
	// 964 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xc7, 0xbb, 0xeb, 0xd8, 0x6e, 0x4f, 0xe2, 0x0f, 0x06, 0xab, 0x5d, 0xdc, 0x50, 0x9b, 0xad,
	0x84, 0x22, 0x0b, 0xd9, 0xad, 0x11, 0x52, 0x89, 0xb8, 0x09, 0x6d, 0x10, 0x91, 0x10, 0x89, 0xd6,
	0x15, 0x17, 0x08, 0xc9, 0x9a, 0x7a, 0x07, 0x67, 0x54, 0xef, 0xcc, 0xe0, 0x19, 0x47, 0x24, 0x88,
	0x1b, 0x24, 0x84, 0x04, 0x57, 0x15, 0xd7, 0x3c, 0x03, 0x2f, 0xc0, 0x5b, 0xf0, 0x0a, 0x3c, 0x05,
	0x57, 0xd5, 0xcc, 0xec, 0xc6, 0xde, 0x5d, 0xc7, 0xde, 0x4a, 0xbd, 0x9b, 0x8f, 0x33, 0xe7, 0xfc,
	0xe6, 0x9c, 0x33, 0xff, 0x5d, 0x68, 0x61, 0x41, 0x07, 0x93, 0x19, 0x5f, 0x84, 0xe1, 0x9c, 0x5e,
	0x90, 0xbe, 0x98, 0x73, 0xc5, 0x51, 0x83, 0x0b, 0xc2, 0xa4, 0xe2, 0x73, 0x3c, 0x25, 0x7d, 0x2c,
	0x68, 0xbb, 0x33, 0xe5, 0x7c, 0x3a, 0x23, 0x03, 0xb3, 0xfd, 0x62, 0xf1, 0xfd, 0x40, 0xd1, 0x88,
	0x48, 0x85, 0x23, 0x61, 0x4f, 0xb4, 0xf7, 0x63, 0x03, 0xed, 0x0e, 0x33, 0xc6, 0x15, 0x56, 0x94,
	0x33, 0x19, 0xef, 0xd6, 0xcc, 0xb2, 0xa0, 0x76, 0xea, 0xff, 0xed, 0x42, 0xed, 0xa9, 0x8e, 0xf9,
	0x4c, 0xc7, 0x1c, 0x11, 0x85, 0xea, 0xe0, 0xd2, 0xd0, 0x73, 0xba, 0xce, 0xc1, 0x9d, 0xc0, 0xa5,
	0x21, 0x1a, 0x42, 0x59, 0x70, 0x3e, 0x93, 0x9e, 0xdb, 0x2d, 0x1d, 0xec, 0x0e, 0xf7, 0xfb, 0x19,
	0xa0, 0xfe, 0xc8, 0x8e, 0xcf, 0x38, 0x9f, 0x05, 0xd6, 0x14, 0x1d, 0x43, 0x73, 0x32, 0x27, 0x58,
	0x91, 0xf1, 0x35, 0x9c, 0x57, 0xea, 0x3a, 0x07, 0xbb, 0xc3, 0x76, 0xdf, 0xd2, 0xf5, 0x13, 0xfc,
	0xfe, 0xf3, 0xc4, 0x22, 0x68, 0xd8, 0x33, 0xd7, 0x0b, 0xe8, 0x53, 0x28, 0x4b, 0x85, 0x15, 0xf1,
	0x76, 0xba, 0xce, 0x41, 0x7d, 0xf8, 0x30, 0x17, 0x3a, 0x45, 0x3e, 0xd2, 0xa6, 0x81, 0x3d, 0x81,
	0x1e, 0x42, 0x8d, 0x32, 0xa9, 0x30, 0x9b, 0x90, 0x31, 0xc3, 0x11, 0xf1, 0xca, 0xe6, 0x42, 0x7b,
	0xc9, 0xe2, 0xd7, 0x38, 0x22, 0xa8, 0x03, 0xbb, 0xd7, 0x46, 0x34, 0xf4, 0x2a, 0xc6, 0x04, 0x92,
	0xa5, 0x93, 0x10, 0x21, 0xd8, 0xb9, 0xe2, 0x8c, 0x78, 0x55, 0xb3, 0x63, 0xc6, 0xfe, 0x37, 0xf0,
	0xfe, 0x28, 0x7c, 0x99, 0x8a, 0xfc, 0xd4, 0x70, 0x07, 0xe4, 0x87, 0x05, 0x91, 0x0a, 0x7d, 0x02,
	0x65, 0x29, 0xc8, 0x44, 0x7a, 0x8e, 0x49, 0x58, 0x67, 0x13, 0xb5, 0x20, 0x93, 0xc0, 0x5a, 0xfb,
	0xff, 0x38, 0x50, 0x4f, 0xef, 0xe8, 0xf0, 0x92, 0x5e, 0x11, 0x53, 0x8c, 0x52, 0x60, 0xc6, 0x7a,
	0x4d, 0x5d, 0x0a, 0xe2, 0xb9, 0x16, 0x49, 0x8f, 0xd1, 0x17, 0x50, 0xe5, 0xc2, 0x14, 0xd9, 0x2b,
	0x99, 0x98, 0x1f, 0x6d, 0x89, 0xd9, 0x3f, 0xb5, 0xe6, 0xc7, 0x4c, 0xcd, 0x2f, 0x83, 0xe4, 0x70,
	0xfb, 0x10, 0xf6, 0x56, 0x37, 0x50, 0x13, 0x4a, 0x2f, 0xc9, 0x65, 0xdc, 0x0b, 0x7a, 0x88, 0x5a,
	0x50, 0xbe, 0xc0, 0xb3, 0x45, 0x12, 0xde, 0x4e, 0x0e, 0xdd, 0x27, 0x8e, 0x7f, 0x0e, 0x0f, 0x6e,
	0x4a, 0x8b, 0x14, 0x9c, 0x49, 0x4d, 0xd9, 0x30, 0xdd, 0x3d, 0x36, 0xed, 0x3d, 0x96, 0x44, 0x19,
	0xcf, 0xbb, 0xc3, 0x07, 0x9b, 0xeb, 0x1a, 0xd4, 0x26, 0xab, 0x53, 0xdf, 0x87, 0x6e, 0x36, 0xd2,
	0x31, 0x5b, 0x44, 0x64, 0xbe, 0xac, 0x81, 0x1f, 0xc1, 0x07, 0x1b, 0x6c, 0x62, 0xa0, 0x2f, 0xa1,
	0x99, 0x01, 0x4a, 0x6a, 0xb6, 0x8d, 0xa8, 0x9e, 0x22, 0x92, 0xfe, 0xa3, 0xfc, 0xe5, 0x4f, 0x98,
	0x2e, 0xab, 0x4a, 0x9a, 0x22, 0xf3, 0xaa, 0x7c, 0x0a, 0x9d, 0x1b, 0x4f, 0xbc, 0xe5, 0x7c, 0x0d,
	0xf2, 0x0d, 0xfb, 0x8c, 0xcc, 0xc8, 0xb2, 0x61, 0xb3, 0x6c, 0xdd, 0xfc, 0x6d, 0x92, 0x03, 0x16,
	0xcd, 0x3f, 0xcb, 0xbb, 0x3c, 0x52, 0x0a, 0x4f, 0xce, 0x6f, 0x70, 0x99, 0x7d, 0x69, 0x6e, 0xf6,
	0xa5, 0xf9, 0x2c, 0x1f, 0x33, 0xf1, 0x18, 0xa7, 0xe3, 0x2b, 0x68, 0x60, 0xb3, 0x42, 0xe2, 0x8c,
	0x24, 0xc5, 0xca, 0xcb, 0xc2, 0x51, 0x6c, 0xb7, 0x74, 0x17, 0xd4, 0x93, 0xb3, 0x66, 0x2a, 0xfd,
	0x27, 0x80, 0xf2, 0x56, 0x39, 0x6c, 0x04, 0x3b, 0x02, 0xab, 0xf3, 0xe4, 0xb1, 0xe9, 0xf1, 0xfa,
	0x74, 0x6e, 0xb8, 0xfb, 0xfa, 0x74, 0xae, 0x5e, 0xcd, 0xff, 0xcb, 0xc9, 0xfb, 0x3c, 0xfe, 0x51,
	0x60, 0x16, 0xde, 0x94, 0xcf, 0x7b, 0x50, 0xd5, 0x4a, 0xbb, 0xcc, 0x65, 0x45, 0x4f, 0x4f, 0x42,
	0x34, 0x82, 0x3a, 0x17, 0xba, 0xcd, 0x29, 0x67, 0x63, 0x23, 0x14, 0x25, 0xa3, 0x9d, 0x79, 0x45,
	0x48, 0x07, 0x3a, 0x4d, 0x0e, 0x3d, 0xbf, 0x14, 0x24, 0xa8, 0xf1, 0xd5, 0xe9, 0xba, 0xb7, 0x9d,
	0xe0, 0xbd, 0xdd, 0x5e, 0xed, 0x7d, 0x07, 0x28, 0xaf, 0xe9, 0xa8, 0x09, 0x7b, 0x94, 0x51, 0x45,
	0xf1, 0x8c, 0x5e, 0x51, 0x36, 0x6d, 0xde, 0x42, 0x7b, 0x70, 0x3b, 0x29, 0x68, 0xd3, 0xd1, 0xb3,
	0x90, 0xc4, 0x33, 0x17, 0x79, 0xd0, 0x12, 0x84, 0x85, 0x94, 0x4d, 0xc7, 0x21, 0x99, 0xf0, 0x28,
	0xa2, 0x52, 0x52, 0xce, 0x9a, 0xa5, 0xde, 0x67, 0x70, 0x7f, 0xc3, 0xad, 0xd1, 0x6d, 0xd8, 0x39,
	0x5a, 0x28, 0xde, 0xbc, 0x85, 0xaa, 0x50, 0x3a, 0x0a, 0xb5, 0x67, 0x80, 0x4a, 0x40, 0xb4, 0xee,
	0x36, 0xdd, 0xe1, 0xff, 0x55, 0xb8, 0x7b, 0x2a, 0x08, 0x8b, 0xbf, 0x77, 0x4b, 0x4e, 0x89, 0xfe,
	0x70, 0xe0, 0xce, 0xb5, 0xbe, 0xa0, 0xc7, 0xf9, 0x4f, 0xe4, 0x16, 0xbd, 0x6a, 0x0f, 0xdf, 0xe4,
	0x48, 0xdc, 0x35, 0xf7, 0x7e, 0xf9, 0xf7, 0xbf, 0x3f, 0xdd, 0x77, 0x50, 0x63, 0x70, 0xf1, 0x78,
	0xe5, 0xbf, 0x41, 0xa2, 0x5f, 0x1d, 0xa8, 0x58, 0xed, 0x45, 0xfd, 0xad, 0x7e, 0x53, 0xdf, 0xae,
	0xf6, 0xa0, 0xb0, 0x7d, 0x0c, 0xd1, 0x36, 0x10, 0x2d, 0x3f, 0x0b, 0x71, 0xe8, 0xf4, 0xd0, 0xef,
	0x0e, 0x54, 0x6c, 0x9e, 0x0b, 0x70, 0xa4, 0xfa, 0xbd, 0x00, 0x47, 0xba, 0x01, 0xfd, 0x8e, 0xe1,
	0x78, 0xaf, 0xdd, 0xca, 0x70, 0x0c, 0x7e, 0xa2, 0xe1, 0xcf, 0x1a, 0xe6, 0x37, 0x07, 0x2a, 0x56,
	0xc5, 0x0a, 0xc0, 0xa4, 0xf4, 0xb1, 0x00, 0x4c, 0x46, 0x1e, 0xf7, 0x0d, 0xcc, 0xdd, 0xde, 0x5a,
	0x18, 0x9d, 0x96, 0x6a, 0xac, 0xf5, 0x68, 0xbb, 0xeb, 0xf4, 0x77, 0xa4, 0xfd, 0xa8, 0xf8, 0x81,
	0x34, 0x0c, 0x5a, 0x0f, 0xf3, 0xca, 0x81, 0x8a, 0x15, 0xc2, 0x02, 0x69, 0x49, 0x69, 0x7c, 0x81,
	0xb4, 0xa4, 0x15, 0xdc, 0xff, 0xd0, 0x90, 0x74, 0xfd, 0xfb, 0xeb, 0x48, 0x06, 0xf6, 0x3d, 0xeb,
	0x52, 0xbd, 0x32, 0xa5, 0x2a, 0xc8, 0x94, 0xd2, 0xde, 0x42, 0xa5, 0x7a, 0x03, 0x26, 0xab, 0x2a,
	0x87, 0x4e, 0xef, 0xf3, 0x7d, 0x78, 0x77, 0xc2, 0xa3, 0xac, 0xf7, 0x33, 0xe7, 0xdb, 0x12, 0x16,
	0xf4, 0x45, 0xc5, 0xfc, 0xcd, 0x7e, 0xfc, 0x3a, 0x00, 0x00, 0xff, 0xff, 0x12, 0xb3, 0x3a, 0xb1,
	0xc3, 0x0b, 0x00, 0x00,
}
