on:
  pull_request_target:
    branches:
      - master
    types: ["closed"]

jobs:
  cherry_pick_release_9_5:
    runs-on: ubuntu-latest
    name: Cherry pick into release-9.5
    if: contains(github.event.pull_request.labels.*.name, 'cherry-pick/release-9.5') && (github.event.pull_request.merged == true)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cherry pick into release-9.5
        uses: ggriffiths/github-cherry-pick-action@v1.0.2-gg
        with:
          branch: release-9.5
          labels: |
            cherry-pick
      - name: Failure message
        if: ${{ failure() }}
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            This pull request cannot be automatically cherry-picked to the target release branch.
            This is likely due to a merge conflict. Please cherry-pick this change yourself and handle the merge conflict.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false
  cherry_pick_release_9_4:
    runs-on: ubuntu-latest
    name: Cherry pick into release-9.4
    if: contains(github.event.pull_request.labels.*.name, 'cherry-pick/release-9.4') && (github.event.pull_request.merged == true)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cherry pick into release-9.4
        uses: ggriffiths/github-cherry-pick-action@v1.0.2-gg
        with:
          branch: release-9.4
          labels: |
            cherry-pick
      - name: Failure message
        if: ${{ failure() }}
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            This pull request cannot be automatically cherry-picked to the target release branch.
            This is likely due to a merge conflict. Please cherry-pick this change yourself and handle the merge conflict.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false
  cherry_pick_release_9_3:
    runs-on: ubuntu-latest
    name: Cherry pick into release-9.3
    if: contains(github.event.pull_request.labels.*.name, 'cherry-pick/release-9.3')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cherry pick into release-9.3
        uses: ggriffiths/github-cherry-pick-action@v1.0.2-gg
        with:
          branch: release-9.3
          labels: |
            cherry-pick
      - name: Failure message
        if: ${{ failure() }}
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            This pull request cannot be automatically cherry-picked to the target release branch.
            This is likely due to a merge conflict. Please cherry-pick this change yourself and handle the merge conflict.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
